const safePath=/^[a-zA-Z_][a-zA-Z0-9_.-]{0,99}$/;
const blocked=new Set(['__proto__','prototype','constructor']);
export const isSafeDataPath=(value:unknown):value is string=>typeof value==='string'&&safePath.test(value)&&!value.split('.').some(part=>blocked.has(part));
export function parseData(value:string):unknown{try{return JSON.parse(value);}catch{return value;}}
export function stringifyData(value:unknown):string{const output=typeof value==='string'?value:JSON.stringify(value);if(Buffer.byteLength(output)>65536)throw new Error('AUTOMATION_DATA_LIMIT');return output;}
function path(value:unknown,key:string):unknown{let current=value;for(const segment of key.split('.')){if(!isSafeDataPath(segment)||!current||typeof current!=='object')return undefined;current=(current as Record<string,unknown>)[segment];}return current;}
export function evaluateSafeExpression(expression:string,variables:Record<string,string>):unknown{const source=expression.trim();if(source.length>4096)throw new Error('AUTOMATION_EXPRESSION_LIMIT');const reference=(raw:string)=>{const key=raw.slice(2);if(!isSafeDataPath(key))throw new Error('AUTOMATION_EXPRESSION_INVALID');return parseData(variables[key]??'');};if(/^\$\.[a-zA-Z_][a-zA-Z0-9_.-]{0,99}$/.test(source))return reference(source);const call=/^(lower|upper|trim|length)\((\$\.[a-zA-Z_][a-zA-Z0-9_.-]{0,99})\)$/.exec(source);if(call){const value=reference(call[2]!),text=typeof value==='string'?value:JSON.stringify(value);return call[1]==='lower'?text.toLowerCase():call[1]==='upper'?text.toUpperCase():call[1]==='trim'?text.trim():Array.isArray(value)||typeof value==='string'?value.length:Object.keys(value&&typeof value==='object'?value:{}).length;}try{return JSON.parse(source);}catch{throw new Error('AUTOMATION_EXPRESSION_INVALID');}}
export function executeDataNode(type:string,data:Record<string,unknown>,variables:Record<string,string>):Record<string,unknown>{const target=data.target;if(!isSafeDataPath(target))throw new Error('AUTOMATION_DATA_TARGET_INVALID');let output:unknown;
 if(type==='data-set')output=data.value;
 else if(type==='data-rename'){const from=data.source;if(!isSafeDataPath(from))throw new Error('AUTOMATION_DATA_SOURCE_INVALID');output=parseData(variables[from]??'');delete variables[from];}
 else if(type==='data-pick'){const source=data.source;if(!isSafeDataPath(source)||!Array.isArray(data.keys))throw new Error('AUTOMATION_DATA_CONFIG_INVALID');const value=parseData(variables[source]??'{}');output=Object.fromEntries(data.keys.filter(isSafeDataPath).map(key=>[key,path(value,key)]));}
 else if(type==='data-merge'){if(!Array.isArray(data.sources))throw new Error('AUTOMATION_DATA_CONFIG_INVALID');output=Object.assign({},...data.sources.filter(isSafeDataPath).map(key=>{const value=parseData(variables[key]??'{}');return value&&typeof value==='object'&&!Array.isArray(value)?value:{};}));}
 else if(type==='data-map'){const source=data.source;if(!isSafeDataPath(source))throw new Error('AUTOMATION_DATA_SOURCE_INVALID');const value=parseData(variables[source]??'[]');if(!Array.isArray(value))throw new Error('AUTOMATION_DATA_ARRAY_REQUIRED');const field=typeof data.field==='string'&&isSafeDataPath(data.field)?data.field:null;output=field?value.map(item=>path(item,field)):value;}
 else if(type==='data-filter'){const source=data.source;if(!isSafeDataPath(source)||!isSafeDataPath(data.field))throw new Error('AUTOMATION_DATA_CONFIG_INVALID');const value=parseData(variables[source]??'[]');if(!Array.isArray(value))throw new Error('AUTOMATION_DATA_ARRAY_REQUIRED');const expected=data.value,operator=data.operator;output=value.filter(item=>{const actual=path(item,data.field as string);return operator==='not_equals'?actual!==expected:operator==='contains'?String(actual).includes(String(expected)):actual===expected;});}
 else if(type==='json-parse'){const source=data.source;if(!isSafeDataPath(source))throw new Error('AUTOMATION_DATA_SOURCE_INVALID');try{output=JSON.parse(variables[source]??'');}catch{throw new Error('AUTOMATION_JSON_INVALID');}}
 else if(type==='json-stringify'){const source=data.source;if(!isSafeDataPath(source))throw new Error('AUTOMATION_DATA_SOURCE_INVALID');output=JSON.stringify(parseData(variables[source]??''));}
 else if(type==='expression'){if(typeof data.expression!=='string')throw new Error('AUTOMATION_EXPRESSION_INVALID');output=evaluateSafeExpression(data.expression,variables);}
 else throw new Error('AUTOMATION_DATA_NODE_UNSUPPORTED');variables[target]=stringifyData(output);return {target,value:output};}
