import { lookup } from 'node:dns/promises';
import { assertPublicAddresses,connectPinnedHttps,type SafeConnectionInput } from '../integrations/chatwoot-safe-http.js';

export interface AutomationHttpRequest {method:'GET'|'POST'|'PUT'|'PATCH'|'DELETE';url:string;headers?:Record<string,string>;body?:string;timeoutMs?:number;maxResponseBytes?:number;redirectLimit?:number;retryAttempts?:number;allowedOrigins?:readonly string[]}
export interface AutomationHttpResponse {status:number;headers:Record<string,string>;body:string;bytes:number;outcome:'success'|'client_error'|'server_error'}
const forbiddenHeaders=new Set(['host','connection','content-length','transfer-encoding','upgrade','proxy-authorization','proxy-authenticate','cookie']);
export function validateAutomationTarget(value:string,allowedOrigins:readonly string[]=[]):URL{const target=new URL(value);if(target.protocol!=='https:'||target.username||target.password||target.hash||!target.hostname)throw new Error('AUTOMATION_HTTP_URL_REJECTED');if(allowedOrigins.length&&!allowedOrigins.includes(target.origin))throw new Error('AUTOMATION_HTTP_ORIGIN_NOT_ALLOWED');return target;}
export function createAutomationSafeHttp(options:{resolve?:(hostname:string)=>Promise<readonly string[]>;connect?:(input:SafeConnectionInput)=>Promise<Response>}){
 const resolve=options.resolve??(async hostname=>(await lookup(hostname,{all:true,verbatim:true})).map(item=>item.address)),connect=options.connect??connectPinnedHttps;
 const executeOnce=async function(input:AutomationHttpRequest):Promise<AutomationHttpResponse>{const maxRequest=1024*1024,maxResponse=Math.min(input.maxResponseBytes??2*1024*1024,4*1024*1024);if(Buffer.byteLength(input.body??'')>maxRequest)throw new Error('AUTOMATION_HTTP_REQUEST_LIMIT');const headers=new Headers(input.headers);for(const name of headers.keys())if(forbiddenHeaders.has(name.toLowerCase()))throw new Error('AUTOMATION_HTTP_HEADER_REJECTED');headers.set('accept-encoding','identity');let target=validateAutomationTarget(input.url,input.allowedOrigins),method=input.method,body=input.body?Buffer.from(input.body):undefined;const limit=Math.min(input.redirectLimit??2,3),deadline=AbortSignal.timeout(Math.min(input.timeoutMs??15000,30000));
  for(let redirect=0;;redirect++){const addresses=Object.freeze([...(await resolve(target.hostname))]);try{assertPublicAddresses(addresses);}catch{throw new Error('AUTOMATION_HTTP_SSRF_REJECTED');}const response=await connect({target,approvedAddresses:addresses,servername:target.hostname,rejectUnauthorized:true,method,headers:Object.fromEntries(headers),body,signal:deadline,maxResponseBytes:maxResponse});
   if(response.status>=300&&response.status<400){if(redirect>=limit)throw new Error('AUTOMATION_HTTP_REDIRECT_LIMIT');const location=response.headers.get('location');await response.body?.cancel();if(!location)throw new Error('AUTOMATION_HTTP_REDIRECT_INVALID');const next=validateAutomationTarget(new URL(location,target).href,input.allowedOrigins);if(next.origin!==target.origin){headers.delete('authorization');headers.delete('api-key');headers.delete('x-api-key');}target=next;if(response.status===303){method='GET';body=undefined;}continue;}
   const buffer=Buffer.from(await response.arrayBuffer());if(buffer.length>maxResponse)throw new Error('AUTOMATION_HTTP_RESPONSE_LIMIT');const outcome=response.status>=500?'server_error':response.status>=400?'client_error':'success';return {status:response.status,headers:Object.fromEntries([...response.headers].filter(([name])=>!['set-cookie','authorization','proxy-authenticate'].includes(name.toLowerCase()))),body:buffer.toString('utf8'),bytes:buffer.length,outcome};}
 };return async (input:AutomationHttpRequest)=>{const retries=input.method==='GET'?Math.min(Math.max(input.retryAttempts??0,0),2):0;for(let attempt=0;;attempt++)try{const response=await executeOnce(input);if(response.outcome==='server_error'&&attempt<retries)continue;return response;}catch(error){const code=error instanceof Error?error.message:'';if(attempt>=retries||(!code.includes('TIMEOUT')&&!code.toLowerCase().includes('aborted')))throw error;}};
}
