import { lookup } from 'node:dns/promises';
import { assertPublicAddresses,connectPinnedHttps,type SafeConnectionInput } from '../integrations/chatwoot-safe-http.js';

export interface AutomationHttpRequest {method:'GET'|'POST'|'PUT'|'PATCH'|'DELETE';url:string;headers?:Record<string,string>;body?:string;timeoutMs?:number;maxResponseBytes?:number;redirectLimit?:number;retryAttempts?:number;allowedOrigins?:readonly string[]}
export interface AutomationHttpResponse {status:number;headers:Record<string,string>;body:string;bytes:number;outcome:'success'|'client_error'|'server_error'}
const httpErrorCodes=['AUTOMATION_HTTP_TIMEOUT','AUTOMATION_HTTP_URL_REJECTED','AUTOMATION_HTTP_ORIGIN_NOT_ALLOWED','AUTOMATION_HTTP_REQUEST_LIMIT','AUTOMATION_HTTP_HEADER_REJECTED','AUTOMATION_HTTP_SSRF_REJECTED','AUTOMATION_HTTP_REDIRECT_LIMIT','AUTOMATION_HTTP_REDIRECT_INVALID','AUTOMATION_HTTP_CROSS_ORIGIN_REDIRECT','AUTOMATION_HTTP_RESPONSE_LIMIT','AUTOMATION_HTTP_REQUEST_INVALID','AUTOMATION_HTTP_DNS_FAILED','AUTOMATION_HTTP_TRANSPORT_FAILED','AUTOMATION_HTTP_RESPONSE_INVALID'] as const;
export type AutomationHttpErrorCode=typeof httpErrorCodes[number];
export function isAutomationHttpErrorCode(value:unknown):value is AutomationHttpErrorCode{return typeof value==='string'&&(httpErrorCodes as readonly string[]).includes(value);}
// dispatched means the connector was invoked, not that the remote action was confirmed.
// No raw transport cause is retained: it can contain URL credentials or headers.
export class AutomationHttpError extends Error {constructor(readonly code:AutomationHttpErrorCode,readonly dispatched:boolean){super(code);this.name='AutomationHttpError';}}
function safeErrorCode(error:unknown,fallback:AutomationHttpErrorCode):AutomationHttpErrorCode{if(error instanceof Error){if((httpErrorCodes as readonly string[]).includes(error.message))return error.message as AutomationHttpErrorCode;if(error.name==='AbortError')return 'AUTOMATION_HTTP_TIMEOUT';if(error.message==='CHATWOOT_RESPONSE_LIMIT')return 'AUTOMATION_HTTP_RESPONSE_LIMIT';if(error.message==='CHATWOOT_INVALID_RESPONSE')return 'AUTOMATION_HTTP_RESPONSE_INVALID';}return fallback;}
const forbiddenHeaders=new Set(['host','connection','content-length','transfer-encoding','upgrade','proxy-authorization','proxy-authenticate','cookie']);
function bounded<T>(operation:()=>Promise<T>,signal:AbortSignal):Promise<T>{
 if(signal.aborted)return Promise.reject(new Error('AUTOMATION_HTTP_TIMEOUT'));
 return new Promise((resolve,reject)=>{const abort=()=>reject(new Error('AUTOMATION_HTTP_TIMEOUT'));signal.addEventListener('abort',abort,{once:true});Promise.resolve().then(()=>{if(signal.aborted)throw new Error('AUTOMATION_HTTP_TIMEOUT');return operation();}).then(value=>{signal.removeEventListener('abort',abort);resolve(value);},error=>{signal.removeEventListener('abort',abort);reject(signal.aborted?new Error('AUTOMATION_HTTP_TIMEOUT'):error);});});
}
export function validateAutomationTarget(value:string,allowedOrigins:readonly string[]=[]):URL{let target:URL;try{target=new URL(value);}catch{throw new Error('AUTOMATION_HTTP_URL_REJECTED');}if(target.protocol!=='https:'||target.username||target.password||target.hash||!target.hostname)throw new Error('AUTOMATION_HTTP_URL_REJECTED');if(allowedOrigins.length&&!allowedOrigins.includes(target.origin))throw new Error('AUTOMATION_HTTP_ORIGIN_NOT_ALLOWED');return target;}
export function createAutomationSafeHttp(options:{resolve?:(hostname:string)=>Promise<readonly string[]>;connect?:(input:SafeConnectionInput)=>Promise<Response>}){
 const resolve=options.resolve??(async hostname=>(await lookup(hostname,{all:true,verbatim:true})).map(item=>item.address)),connect=options.connect??connectPinnedHttps;
 const executeOnce=async function(input:AutomationHttpRequest):Promise<AutomationHttpResponse>{let dispatched=false,fallback:AutomationHttpErrorCode='AUTOMATION_HTTP_REQUEST_INVALID';try{const maxRequest=1024*1024,maxResponse=Math.min(input.maxResponseBytes??2*1024*1024,4*1024*1024);if(Buffer.byteLength(input.body??'')>maxRequest)throw new Error('AUTOMATION_HTTP_REQUEST_LIMIT');let headers:Headers;try{headers=new Headers(input.headers);}catch{throw new Error('AUTOMATION_HTTP_HEADER_REJECTED');}for(const name of headers.keys())if(forbiddenHeaders.has(name.toLowerCase()))throw new Error('AUTOMATION_HTTP_HEADER_REJECTED');headers.set('accept-encoding','identity');let target=validateAutomationTarget(input.url,input.allowedOrigins),method=input.method,body=input.body?Buffer.from(input.body):undefined;const limit=Math.min(input.redirectLimit??2,3),deadline=AbortSignal.timeout(Math.min(input.timeoutMs??15000,30000));
  for(let redirect=0;;redirect++){fallback='AUTOMATION_HTTP_DNS_FAILED';const addresses=Object.freeze([...(await bounded(()=>resolve(target.hostname),deadline))]);try{assertPublicAddresses(addresses);}catch{throw new Error('AUTOMATION_HTTP_SSRF_REJECTED');}fallback='AUTOMATION_HTTP_TRANSPORT_FAILED';const response=await bounded(()=>{dispatched=true;return connect({target,approvedAddresses:addresses,servername:target.hostname,rejectUnauthorized:true,method,headers:Object.fromEntries(headers),body,signal:deadline,maxResponseBytes:maxResponse});},deadline);fallback='AUTOMATION_HTTP_RESPONSE_INVALID';
   if(response.status>=300&&response.status<400){const location=response.headers.get('location');await response.body?.cancel();if(redirect>=limit)throw new Error('AUTOMATION_HTTP_REDIRECT_LIMIT');if(!location)throw new Error('AUTOMATION_HTTP_REDIRECT_INVALID');const next=validateAutomationTarget(new URL(location,target).href,input.allowedOrigins);if(next.origin!==target.origin){if(method!=='GET'||body)throw new Error('AUTOMATION_HTTP_CROSS_ORIGIN_REDIRECT');for(const name of [...headers.keys()])headers.delete(name);headers.set('accept-encoding','identity');}target=next;if(response.status===303){method='GET';body=undefined;headers.delete('content-type');}continue;}
   const buffer=Buffer.from(await bounded(()=>response.arrayBuffer(),deadline));if(buffer.length>maxResponse)throw new Error('AUTOMATION_HTTP_RESPONSE_LIMIT');const outcome=response.status>=500?'server_error':response.status>=400?'client_error':'success';return {status:response.status,headers:Object.fromEntries([...response.headers].filter(([name])=>!['set-cookie','authorization','proxy-authenticate'].includes(name.toLowerCase()))),body:buffer.toString('utf8'),bytes:buffer.length,outcome};}
 }catch(error){throw new AutomationHttpError(safeErrorCode(error,fallback),dispatched);}};return async (input:AutomationHttpRequest)=>{const retries=input.method==='GET'?Math.min(Math.max(input.retryAttempts??0,0),2):0;for(let attempt=0;;attempt++)try{const response=await executeOnce(input);if(response.outcome==='server_error'&&attempt<retries)continue;return response;}catch(error){if(attempt>=retries||!(error instanceof AutomationHttpError)||error.code!=='AUTOMATION_HTTP_TIMEOUT')throw error;}};
}
