import {Client} from 'pg';
import mysql from 'mysql2/promise';

const prohibited=/\b(?:insert|update|delete|merge|copy|call|do|create|alter|drop|truncate|grant|revoke|set|reset|vacuum|analyze|refresh|reindex|cluster|listen|notify|load|outfile|dumpfile|lock|unlock)\b/iu;
export function assertReadOnlySql(query:string):string{const value=query.trim();if(!value||value.length>50000||value.includes('\0')||value.split(';').filter(part=>part.trim()).length>1||prohibited.test(value)||!/^(?:select\b|with\b)/iu.test(value))throw new Error('AUTOMATION_SQL_READ_ONLY_REQUIRED');return value.replace(/;\s*$/u,'');}
export interface SqlResult{rows:Record<string,unknown>[];rowCount:number;truncated:boolean;durationMs:number}
export async function executeReadOnlySql(input:{type:'POSTGRES'|'MYSQL';connectionString:string;query:string;parameters:unknown[];timeoutMs?:number;maxRows?:number}):Promise<SqlResult>{const query=assertReadOnlySql(input.query),timeout=Math.min(Math.max(input.timeoutMs??5000,100),30000),maxRows=Math.min(Math.max(input.maxRows??100,1),1000),started=Date.now();
 if(input.type==='POSTGRES'){const url=new URL(input.connectionString);if(!['postgres:','postgresql:'].includes(url.protocol))throw new Error('AUTOMATION_SQL_CREDENTIAL_INVALID');const client=new Client({connectionString:input.connectionString,ssl:{rejectUnauthorized:true},connectionTimeoutMillis:timeout});await client.connect();try{await client.query('BEGIN READ ONLY');await client.query(`SET LOCAL statement_timeout = ${timeout}`);const result=await client.query<Record<string,unknown>>(`SELECT * FROM (${query}) AS jrc_readonly_result LIMIT ${maxRows+1}`,input.parameters);await client.query('COMMIT');return {rows:result.rows.slice(0,maxRows),rowCount:Math.min(result.rows.length,maxRows),truncated:result.rows.length>maxRows,durationMs:Date.now()-started};}catch(error){await client.query('ROLLBACK').catch(()=>undefined);throw error;}finally{await client.end();}}
 const url=new URL(input.connectionString);if(url.protocol!=='mysql:')throw new Error('AUTOMATION_SQL_CREDENTIAL_INVALID');const parameters=input.parameters.map(value=>value===null||['string','number','boolean'].includes(typeof value)?value:JSON.stringify(value)) as Array<string|number|boolean|null>;const connection=await mysql.createConnection({host:url.hostname,port:Number(url.port||3306),user:decodeURIComponent(url.username),password:decodeURIComponent(url.password),database:url.pathname.slice(1),ssl:{rejectUnauthorized:true},connectTimeout:timeout,multipleStatements:false});try{await connection.query('SET SESSION MAX_EXECUTION_TIME = ?',[timeout]);await connection.query('START TRANSACTION READ ONLY');const [raw]=await connection.execute(`SELECT * FROM (${query}) AS jrc_readonly_result LIMIT ${maxRows+1}`,parameters);await connection.query('COMMIT');const rows=(Array.isArray(raw)?raw:[]) as Record<string,unknown>[];return {rows:rows.slice(0,maxRows),rowCount:Math.min(rows.length,maxRows),truncated:rows.length>maxRows,durationMs:Date.now()-started};}catch(error){await connection.query('ROLLBACK').catch(()=>undefined);throw error;}finally{await connection.end();}}
