import {createHash,createHmac,randomBytes,randomUUID,timingSafeEqual} from 'node:crypto';
import type {Pool} from 'pg';
import type {OrganizationTransaction,TenantTransaction} from '../../db/tenant-transaction.js';
import type {CredentialService} from './credentials.js';
import type {ReturnTypeOfEventRouter} from './webhooks.types.js';

interface WebhookRow{id:string;organizationId:string;bindingId:string;hmacCredentialId:string|null;status:'ACTIVE'|'REVOKED';createdAt:Date;updatedAt:Date}
export interface WebhookRepository{list(tx:TenantTransaction,org:string):Promise<WebhookRow[]>;insert(tx:TenantTransaction,row:{org:string;id:string;bindingId:string;tokenHash:string;hmacCredentialId:string|null}):Promise<WebhookRow>;revoke(tx:TenantTransaction,org:string,id:string):Promise<boolean>}
const columns=`id,organization_id AS "organizationId",binding_id AS "bindingId",hmac_credential_id AS "hmacCredentialId",status,created_at AS "createdAt",updated_at AS "updatedAt"`;
export function createPostgresWebhookRepository():WebhookRepository{return {list:async(tx,org)=>(await tx.query<WebhookRow>(`select ${columns} from automation_webhooks where organization_id=$1 order by created_at desc`,[org])).rows,insert:async(tx,row)=>(await tx.query<WebhookRow>(`insert into automation_webhooks(organization_id,id,binding_id,token_hash,hmac_credential_id) select $1,$2,b.id,$4,$5 from automation_bindings b where b.organization_id=$1 and b.id=$3 returning ${columns}`,[row.org,row.id,row.bindingId,row.tokenHash,row.hmacCredentialId])).rows[0]!,revoke:async(tx,org,id)=>Boolean((await tx.query(`update automation_webhooks set status='REVOKED',updated_at=now() where organization_id=$1 and id=$2 and status='ACTIVE'`,[org,id])).rowCount)};}
const hash=(token:string)=>createHash('sha256').update(token).digest('hex'),view=(row:WebhookRow)=>({...row,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString()});
export function verifyAutomationHook(secret:string,body:Buffer,timestamp:string|undefined,signature:string|undefined,now=Date.now()){if(!timestamp||!/^\d{10}$/.test(timestamp)||!signature||!/^sha256=[a-f0-9]{64}$/.test(signature)||Math.abs(now-Number(timestamp)*1000)>300000)return false;const expected=createHmac('sha256',secret).update(timestamp+'.').update(body).digest(),given=Buffer.from(signature.slice(7),'hex');return given.length===expected.length&&timingSafeEqual(expected,given);}
export function createWebhookService(options:{pool:Pool;transact<T>(org:string,work:OrganizationTransaction<T>):Promise<T>;credentials:CredentialService;router:ReturnTypeOfEventRouter;repository?:WebhookRepository}){const repository=options.repository??createPostgresWebhookRepository();return {list:(org:string)=>options.transact(org,async tx=>({data:(await repository.list(tx,org)).map(view)})),create:(org:string,input:{bindingId:string;hmacCredentialId?:string})=>options.transact(org,async tx=>{if(input.hmacCredentialId)await options.credentials.get(org,input.hmacCredentialId);const token=randomBytes(32).toString('base64url'),row=await repository.insert(tx,{org,id:randomUUID(),bindingId:input.bindingId,tokenHash:hash(token),hmacCredentialId:input.hmacCredentialId??null});if(!row)throw new Error('AUTOMATION_BINDING_NOT_FOUND');return {...view(row),token,path:`/hooks/${token}`};}),revoke:(org:string,id:string)=>options.transact(org,async tx=>({ok:await repository.revoke(tx,org,id)})),receive:async(token:string,eventId:string,payload:Record<string,unknown>,timestamp?:string,signature?:string)=>{const record=(await options.pool.query<{organization_id:string;webhook_id:string;binding_id:string;channel_id:string;hmac_credential_id:string|null}>('select * from automation_resolve_webhook($1)',[hash(token)])).rows[0];if(!record)throw new Error('WEBHOOK_NOT_FOUND');const raw=Buffer.from(JSON.stringify(payload));if(record.hmac_credential_id){const credential=await options.credentials.resolve(record.organization_id,record.hmac_credential_id),secret=credential.secret.secret;if(typeof secret!=='string'||!verifyAutomationHook(secret,raw,timestamp,signature))throw new Error('WEBHOOK_SIGNATURE_INVALID');}const routed=await options.router.route(record.organization_id,{channelId:record.channel_id,eventKey:`webhook:${record.webhook_id}:${eventId}`,text:typeof payload.text==='string'?payload.text:'',payload:{...payload,eventType:'WEBHOOK'}});return {accepted:true,duplicate:routed.duplicate,execution:routed.execution?.id??null};}};}
