import { createHash, randomUUID } from 'node:crypto';
import { AUTOMATION_ORIGIN, AutomationGraphV1Schema, FLOW_ORIGIN, type AutomationGraphV1 } from '@jrc/contracts';
import type { OrganizationTransaction, TenantTransaction } from '../../db/tenant-transaction.js';
import { validateAutomationGraph } from './engine.js';
import { AutomationError } from './service.js';

const stable=(value:unknown):unknown=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,child])=>[key,stable(child)])):value;
export const legacyArtifactChecksum=(value:unknown)=>createHash('sha256').update(JSON.stringify(stable(value))).digest('hex');
const bindingId=(org:string,flow:string,channel:string)=>{const hex=createHash('sha256').update(`${org}:${flow}:${channel}`).digest('hex');return `${hex.slice(0,8)}-${hex.slice(8,12)}-4${hex.slice(13,16)}-a${hex.slice(17,20)}-${hex.slice(20,32)}`;};
interface LegacyFlow {id:string;name:string;graph:unknown;revision:number;publishedVersion:number|null;updatedAt:Date}
interface Version {version:number;graph:unknown;createdAt:Date}
interface Ledger {status:string;sourceChecksum:string|null;automationId:string|null}
export interface LegacyMigrationOptions {transact<T>(org:string,work:OrganizationTransaction<T>):Promise<T>}
export function createLegacyFlowMigrationService(options:LegacyMigrationOptions){
 async function liveCount(tx:TenantTransaction,org:string,flowId:string,channelId:string){return Number((await tx.query<{count:number}>(`select ((select count(*) from flow_sessions s join messaging_conversations c on c.organization_id=s.organization_id and c.id=s.conversation_id where s.organization_id=$1 and s.flow_id=$2 and c.channel_id=$3 and s.state->>'status'='waiting')+(select count(*) from messaging_bot_jobs j join messaging_conversations c on c.organization_id=j.organization_id and c.id=j.conversation_id where j.organization_id=$1 and c.channel_id=$3 and j.status='RUNNING'))::int count`,[org,flowId,channelId])).rows[0]?.count??0);}
 async function switchOwner(tx:TenantTransaction,input:{org:string;flowId:string;channelId:string;automationId:string;actorId?:string}){const live=await liveCount(tx,input.org,input.flowId,input.channelId);if(live)return {status:'WAITING_FOR_DRAIN' as const,live};
  const current=(await tx.query<{bot_origin_reference:string|null;bot_public_id:string|null}>(`select bot_origin_reference,bot_public_id from messaging_channels where organization_id=$1 and id=$2 for update`,[input.org,input.channelId])).rows[0];
  if(current?.bot_origin_reference===AUTOMATION_ORIGIN&&current.bot_public_id===input.automationId)return {status:'MANAGED' as const,live:0};
  if(!current||current.bot_origin_reference!==FLOW_ORIGIN||current.bot_public_id!==input.flowId)return {status:'CONFLICT' as const,live:0};
  await tx.query(`update automation_bindings set status='ACTIVE',revision=revision+1,updated_at=now() where organization_id=$1 and automation_id=$2 and channel_id=$3 and status='PAUSED'`,[input.org,input.automationId,input.channelId]);
  await tx.query(`update messaging_channels set bot_origin_reference=$4,bot_public_id=$2,updated_at=now() where organization_id=$1 and id=$3`,[input.org,input.automationId,input.channelId,AUTOMATION_ORIGIN]);
  await tx.query(`insert into automation_owner_transitions(organization_id,channel_id,from_origin,to_origin,automation_id,actor_id,reason_code) values($1,$2,$3,$4,$5,$6,'LEGACY_FLOW_CUTOVER')`,[input.org,input.channelId,FLOW_ORIGIN,AUTOMATION_ORIGIN,input.automationId,input.actorId??null]);return {status:'MANAGED' as const,live:0};}
 async function migrateOne(tx:TenantTransaction,org:string,flow:LegacyFlow,actorId?:string){const versions=(await tx.query<Version>(`select version,graph,created_at as "createdAt" from flow_versions where organization_id=$1 and flow_id=$2 order by version`,[org,flow.id])).rows,sourceChecksum=legacyArtifactChecksum({draft:flow.graph,versions:versions.map(item=>({version:item.version,graph:item.graph}))}),ledger=(await tx.query<Ledger>(`select status,source_checksum as "sourceChecksum",automation_id as "automationId" from automation_legacy_migrations where organization_id=$1 and source='BROKER_FLOW_V1' and source_id=$2 for update`,[org,flow.id])).rows[0];
  if(ledger?.sourceChecksum===sourceChecksum&&['MANAGED','WAITING_FOR_DRAIN','CONVERTED','LEGACY'].includes(ledger.status))return {flowId:flow.id,status:ledger.status,checksum:sourceChecksum,skipped:true};
  if(ledger?.sourceChecksum&&ledger.sourceChecksum!==sourceChecksum){const report={errors:['LEGACY_SOURCE_CHANGED'],previousChecksum:ledger.sourceChecksum,currentChecksum:sourceChecksum};await tx.query(`update automation_legacy_migrations set status='CONFLICT',report=$3,updated_at=now() where organization_id=$1 and source='BROKER_FLOW_V1' and source_id=$2`,[org,flow.id,JSON.stringify(report)]);if(ledger.automationId)await tx.query(`update automation_definitions set migration_status='CONFLICT' where organization_id=$1 and id=$2`,[org,ledger.automationId]);return {flowId:flow.id,status:'CONFLICT' as const,checksum:sourceChecksum,errors:report.errors};}
  const parsed=AutomationGraphV1Schema.safeParse(flow.graph),errors=parsed.success?validateAutomationGraph(parsed.data):['AUTOMATION_GRAPH_UNSUPPORTED'];if(!parsed.success||errors.length){await tx.query(`insert into automation_legacy_migrations(organization_id,source,source_id,source_version,source_checksum,status,report) values($1,'BROKER_FLOW_V1',$2,$3,$4,'LEGACY',$5) on conflict(organization_id,source,source_id) do update set source_version=$3,source_checksum=$4,status='LEGACY',report=$5,updated_at=now()`,[org,flow.id,flow.publishedVersion,sourceChecksum,JSON.stringify({errors})]);return {flowId:flow.id,status:'LEGACY',checksum:sourceChecksum,errors};}
  const graph=parsed.data as AutomationGraphV1,existing=(await tx.query<{origin:string}>(`select origin from automation_definitions where organization_id=$1 and id=$2`,[org,flow.id])).rows[0];if(existing&&existing.origin!=='BROKER_FLOW_V1'){await tx.query(`insert into automation_legacy_migrations(organization_id,source,source_id,source_version,source_checksum,status,report) values($1,'BROKER_FLOW_V1',$2,$3,$4,'CONFLICT',$5) on conflict(organization_id,source,source_id) do update set status='CONFLICT',report=$5,updated_at=now()`,[org,flow.id,flow.publishedVersion,sourceChecksum,JSON.stringify({errors:['AUTOMATION_ID_CONFLICT']})]);return {flowId:flow.id,status:'CONFLICT',checksum:sourceChecksum};}
  await tx.query(`insert into automation_definitions(organization_id,id,name,lifecycle_status,draft_graph,draft_revision,active_version,created_at,updated_at,origin,external_id,migration_status) values($1,$2,$3,$4,$5,$6,null,$7,$7,'BROKER_FLOW_V1',$8,'CONVERTED') on conflict(organization_id,id) do update set name=$3,draft_graph=$5,draft_revision=$6,external_id=$8,migration_status='CONVERTED',updated_at=now()`,[org,flow.id,flow.name,flow.publishedVersion?'PUBLISHED':'DRAFT',JSON.stringify(graph),flow.revision,flow.updatedAt,`legacy-flow:${flow.id}`]);
  for(const version of versions){const versionGraph=AutomationGraphV1Schema.parse(version.graph),versionChecksum=legacyArtifactChecksum(versionGraph);await tx.query(`insert into automation_versions(organization_id,automation_id,version,graph,checksum,published_at) values($1,$2,$3,$4,$5,$6) on conflict(organization_id,automation_id,version) do nothing`,[org,flow.id,version.version,JSON.stringify(versionGraph),versionChecksum,version.createdAt]);}
  if(flow.publishedVersion)await tx.query(`update automation_definitions set active_version=$3 where organization_id=$1 and id=$2`,[org,flow.id,flow.publishedVersion]);
  const channels=flow.publishedVersion?(await tx.query<{id:string}>(`select id from messaging_channels where organization_id=$1 and bot_origin_reference=$2 and bot_public_id=$3`,[org,FLOW_ORIGIN,flow.id])).rows:[];let managed=0,waiting=0,conflicts=0,live=0;
  for(const channel of channels){const id=bindingId(org,flow.id,channel.id);await tx.query(`insert into automation_bindings(organization_id,id,automation_id,version,channel_id,status) values($1,$2,$3,$4,$5,'PAUSED') on conflict(organization_id,id) do nothing`,[org,id,flow.id,flow.publishedVersion,channel.id]);const switched=await switchOwner(tx,{org,flowId:flow.id,channelId:channel.id,automationId:flow.id,...(actorId?{actorId}:{})});live+=switched.live;if(switched.status==='MANAGED')managed++;else if(switched.status==='WAITING_FOR_DRAIN')waiting++;else conflicts++;}
  const status=conflicts?'CONFLICT':waiting?'WAITING_FOR_DRAIN':managed?'MANAGED':'CONVERTED',targetChecksum=legacyArtifactChecksum(graph);await tx.query(`insert into automation_legacy_migrations(organization_id,source,source_id,automation_id,source_version,source_checksum,target_checksum,status,binding_count,live_execution_count,report) values($1,'BROKER_FLOW_V1',$2::text,$2::uuid,$3,$4,$5,$6,$7,$8,$9) on conflict(organization_id,source,source_id) do update set automation_id=$2::uuid,source_version=$3,source_checksum=$4,target_checksum=$5,status=$6,binding_count=$7,live_execution_count=$8,report=$9,updated_at=now()`,[org,flow.id,flow.publishedVersion,sourceChecksum,targetChecksum,status,channels.length,live,JSON.stringify({managed,waiting,conflicts,versions:versions.length})]);await tx.query(`update automation_definitions set migration_status=$3 where organization_id=$1 and id=$2`,[org,flow.id,status]);return {flowId:flow.id,status,checksum:sourceChecksum,targetChecksum,bindings:channels.length,live};}
 return {
  migrateBatch:(org:string,input:{limit?:number;actorId?:string}={})=>options.transact(org,async tx=>{const limit=Math.min(Math.max(input.limit??50,1),200),flows=(await tx.query<LegacyFlow>(`select id,name,graph,revision,published_version as "publishedVersion",updated_at as "updatedAt" from flows where organization_id=$1 order by id limit $2`,[org,limit])).rows,items=[];for(const flow of flows)items.push(await migrateOne(tx,org,flow,input.actorId));return {organizationId:org,count:items.length,checksum:legacyArtifactChecksum(items.map(item=>({flowId:item.flowId,checksum:item.checksum,status:item.status}))),items};}),
  cutover:(org:string,flowId:string,actorId:string)=>options.transact(org,async tx=>{const ledger=(await tx.query<{automationId:string|null}>(`select automation_id as "automationId" from automation_legacy_migrations where organization_id=$1 and source='BROKER_FLOW_V1' and source_id=$2 for update`,[org,flowId])).rows[0];if(!ledger?.automationId)throw new AutomationError('LEGACY_FLOW_NOT_CONVERTED',409);const channels=(await tx.query<{id:string}>(`select channel_id as id from automation_bindings where organization_id=$1 and automation_id=$2 and status in ('PAUSED','ACTIVE') order by channel_id`,[org,ledger.automationId])).rows,results=[];for(const channel of channels)results.push(await switchOwner(tx,{org,flowId,channelId:channel.id,automationId:ledger.automationId,actorId}));const waiting=results.reduce((sum,item)=>sum+item.live,0),status=results.some(item=>item.status==='CONFLICT')?'CONFLICT':waiting?'WAITING_FOR_DRAIN':'MANAGED';await tx.query(`update automation_legacy_migrations set status=$3,live_execution_count=$4,updated_at=now() where organization_id=$1 and source='BROKER_FLOW_V1' and source_id=$2`,[org,flowId,status,waiting]);await tx.query(`update automation_definitions set migration_status=$3 where organization_id=$1 and id=$2`,[org,flowId,status]);return {flowId,status,results};}),
  rollback:(org:string,flowId:string,actorId:string)=>options.transact(org,async tx=>{const active=Number((await tx.query<{count:number}>(`select count(*)::int count from automation_executions where organization_id=$1 and automation_id=$2 and status in ('QUEUED','RUNNING','WAITING','UNKNOWN')`,[org,flowId])).rows[0]?.count??0);if(active)throw new AutomationError('AUTOMATION_ROLLBACK_ACTIVE_EXECUTIONS',409);const channels=(await tx.query<{id:string}>(`select id from messaging_channels where organization_id=$1 and bot_origin_reference=$2 and bot_public_id=$3 for update`,[org,AUTOMATION_ORIGIN,flowId])).rows;for(const channel of channels){await tx.query(`update automation_bindings set status='DISABLED',revision=revision+1,updated_at=now() where organization_id=$1 and automation_id=$2 and channel_id=$3`,[org,flowId,channel.id]);await tx.query(`update messaging_channels set bot_origin_reference=$3,bot_public_id=$2,updated_at=now() where organization_id=$1 and id=$4`,[org,flowId,FLOW_ORIGIN,channel.id]);await tx.query(`insert into automation_owner_transitions(organization_id,channel_id,from_origin,to_origin,automation_id,actor_id,reason_code) values($1,$2,$3,$4,$5,$6,'ROLLBACK_TO_LEGACY_FLOW')`,[org,channel.id,AUTOMATION_ORIGIN,FLOW_ORIGIN,flowId,actorId]);}await tx.query(`update automation_legacy_migrations set status='ROLLED_BACK',updated_at=now() where organization_id=$1 and source='BROKER_FLOW_V1' and source_id=$2`,[org,flowId]);await tx.query(`update automation_definitions set migration_status='ROLLED_BACK' where organization_id=$1 and id=$2`,[org,flowId]);return {flowId,status:'ROLLED_BACK',channels:channels.length};}),
  status:(org:string)=>options.transact(org,async tx=>({data:(await tx.query(`select source,source_id as "sourceId",automation_id as "automationId",source_version as "sourceVersion",source_checksum as "sourceChecksum",target_checksum as "targetChecksum",status,binding_count as "bindingCount",live_execution_count as "liveExecutionCount",report,updated_at as "updatedAt" from automation_legacy_migrations where organization_id=$1 order by updated_at desc`,[org])).rows,metrics:(await tx.query(`select (select count(*)::int from flows where organization_id=$1) as "legacyFlows",(select count(*)::int from flow_runs where organization_id=$1) as "legacyExecutions",(select count(*)::int from messaging_channels where organization_id=$1 and bot_origin_reference=$2) as "legacyBindings",(select count(*)::int from automation_legacy_migrations where organization_id=$1 and status='LEGACY') as "conversionFailures"`,[org,FLOW_ORIGIN])).rows[0]})),
 };
}
export type LegacyFlowMigrationService=ReturnType<typeof createLegacyFlowMigrationService>;
