import { describe,expect,it,vi } from 'vitest';
import type { TenantTransaction } from '../../src/db/tenant-transaction.js';
import { createCredentialService,createCredentialVault,type CredentialRepository,type CredentialRow } from '../../src/modules/automation-integrations/credentials.js';

const org='92776cb0-bcba-45c0-98a3-2937fefdfdaf',key=Buffer.alloc(32,7).toString('base64');
function fixture(testBudget?:Parameters<typeof createCredentialService>[0]['testBudget']){const rows=new Map<string,CredentialRow>();const repository:CredentialRepository={
 list:async()=>[...rows.values()],get:async(_tx,_org,id)=>rows.get(id)??null,
 insert:async(_tx,value)=>{const row={id:value.id,organizationId:value.org,name:value.name,type:value.type,encryptedSecret:value.encrypted,keyVersion:value.keyVersion,fingerprint:value.fingerprint,metadata:value.metadata,status:'ACTIVE' as const,revision:1,lastTestedAt:null,createdAt:new Date('2026-09-21T12:00:00Z'),updatedAt:new Date('2026-09-21T12:00:00Z')};rows.set(row.id,row);return row;},
 rotate:async(_tx,value)=>{const row=rows.get(value.id);if(!row||row.revision!==value.revision)return null;const next={...row,encryptedSecret:value.encrypted,keyVersion:value.keyVersion,fingerprint:value.fingerprint,revision:row.revision+1};rows.set(row.id,next);return next;},
 revoke:async(_tx,_org,id,revision)=>{const row=rows.get(id);if(!row||row.revision!==revision)return null;const next={...row,encryptedSecret:null,status:'REVOKED' as const,revision:row.revision+1};rows.set(id,next);return next;},
 tested:async(_tx,_org,id)=>{const row=rows.get(id)!;const next={...row,lastTestedAt:new Date()};rows.set(id,next);return next;},
 };let transactions=0;const tester={test:vi.fn(async()=>undefined)},service=createCredentialService({transact:async(_org,work)=>{transactions++;try{return await work({} as TenantTransaction);}finally{transactions--;}},vault:createCredentialVault(JSON.stringify({1:key})),repository,tester,...(testBudget?{testBudget}:{})});return {service,rows,tester,get transactions(){return transactions;}};}
describe('credential vault',()=>{
 it('enforces the distributed organization budget before decrypting or opening a connection',async()=>{const consume=vi.fn(async()=>({allowed:false,count:11,remaining:0,retryAfterMs:1000,released:false}));const h=fixture({store:{kind:'redis',consume},secret:'test-secret-with-at-least-32-bytes'});await expect(h.service.test(org,'unknown')).rejects.toMatchObject({code:'CREDENTIAL_TEST_RATE_LIMITED',statusCode:429});expect(consume).toHaveBeenCalledWith(expect.stringMatching(/^identity:[a-f0-9]{64}$/),10,60000);expect(h.tester.test).not.toHaveBeenCalled();});
 it('fails closed when the distributed credential budget is unavailable',async()=>{const consume=vi.fn(async()=>{throw new Error('offline');});const h=fixture({store:{kind:'redis',consume},secret:'test-secret-with-at-least-32-bytes'});await expect(h.service.test(org,'unknown')).rejects.toMatchObject({code:'CREDENTIAL_TEST_UNAVAILABLE',statusCode:503});expect(h.tester.test).not.toHaveBeenCalled();});
 it('releases the tenant database connection during remote testing',async()=>{const h=fixture(),created=await h.service.create(org,{name:'External',type:'BEARER',secret:{token:'fake'},metadata:{}});h.tester.test.mockImplementation(async()=>{expect(h.transactions).toBe(0);});await h.service.test(org,created.id);expect(h.rows.get(created.id)?.lastTestedAt).not.toBeNull();});
 it('does not mark a rotated credential as tested with an old secret',async()=>{const h=fixture(),created=await h.service.create(org,{name:'External',type:'BEARER',secret:{token:'fake'},metadata:{}});h.tester.test.mockImplementation(async()=>{await h.service.rotate(org,created.id,{revision:1,secret:{token:'new'}});});await expect(h.service.test(org,created.id)).rejects.toMatchObject({code:'CREDENTIAL_CHANGED',statusCode:409});expect(h.rows.get(created.id)?.lastTestedAt).toBeNull();});
 it('limits concurrent external tests per organization and releases its slot after completion',async()=>{const h=fixture(),created=await h.service.create(org,{name:'External',type:'BEARER',secret:{token:'fake'},metadata:{}});let finish!:()=>void;let entered!:()=>void;const ready=new Promise<void>(resolve=>{entered=resolve;});h.tester.test.mockImplementation(()=>{entered();return new Promise<void>(resolve=>{finish=resolve;});});const first=h.service.test(org,created.id);await ready;await expect(h.service.test(org,created.id)).rejects.toMatchObject({code:'CREDENTIAL_TEST_BUSY',statusCode:429});finish();await first;h.tester.test.mockResolvedValue(undefined);await expect(h.service.test(org,created.id)).resolves.toHaveProperty('lastTestedAt');});
 it('returns metadata but never encrypted material or the secret',async()=>{const h=fixture(),created=await h.service.create(org,{name:'Meta',type:'BEARER',secret:{token:'canary-never-return'},metadata:{provider:'meta'}});expect(JSON.stringify(created)).not.toContain('canary');expect(JSON.stringify(created)).not.toContain('encrypted');const row=h.rows.get(created.id)!;expect(row.encryptedSecret).not.toContain('canary');await h.service.test(org,created.id);expect(h.tester.test).toHaveBeenCalledWith('BEARER',{token:'canary-never-return'},{provider:'meta'});});
 it('binds ciphertext to tenant, type and record through AAD',async()=>{const vault=createCredentialVault(JSON.stringify({1:key})),sealed=vault.seal(org,'BEARER','11111111-2222-4333-8444-555555555555',{token:'secret'}),row={organizationId:org,type:'BEARER',id:'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee',keyVersion:1,status:'ACTIVE',encryptedSecret:sealed.encrypted} as CredentialRow;expect(()=>vault.open(row)).toThrow('INTEGRATION_SECRET_UNAVAILABLE');});
 it('deletes ciphertext on revocation',async()=>{const h=fixture(),created=await h.service.create(org,{name:'Banco',type:'POSTGRES',secret:{url:'postgres://example'},metadata:{}});await h.service.revoke(org,created.id,created.revision);expect(h.rows.get(created.id)?.encryptedSecret).toBeNull();});
});
