DO $$
BEGIN
  IF current_user <> 'jrc_migrator' THEN
    RAISE EXCEPTION 'migrations must run as jrc_migrator'
      USING ERRCODE = '42501';
  END IF;
END
$$;
--> statement-breakpoint
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO jrc_migrator;
GRANT USAGE ON SCHEMA public TO jrc_app, jrc_auth;
ALTER DEFAULT PRIVILEGES FOR ROLE jrc_migrator IN SCHEMA public
  REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE jrc_migrator IN SCHEMA public
  REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE jrc_migrator IN SCHEMA public
  REVOKE ALL ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE jrc_migrator IN SCHEMA public
  REVOKE ALL ON TYPES FROM PUBLIC;
