CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'jrc_platform') THEN
    CREATE ROLE jrc_platform LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'jrc_migrator') THEN
    CREATE ROLE jrc_migrator NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'jrc_app') THEN
    CREATE ROLE jrc_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'jrc_auth') THEN
    CREATE ROLE jrc_auth LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END
$$;

ALTER ROLE jrc_migrator NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
ALTER ROLE jrc_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
ALTER ROLE jrc_auth LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
ALTER ROLE jrc_platform LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;

DO $$
BEGIN
  EXECUTE format('GRANT CREATE ON DATABASE %I TO jrc_migrator', current_database());
END
$$;

ALTER SCHEMA public OWNER TO jrc_migrator;
CREATE SCHEMA IF NOT EXISTS drizzle AUTHORIZATION jrc_migrator;
ALTER SCHEMA drizzle OWNER TO jrc_migrator;
REVOKE ALL ON SCHEMA public, drizzle FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public, drizzle TO jrc_migrator;
GRANT USAGE ON SCHEMA public TO jrc_app, jrc_auth, jrc_platform;
