export const jrcTokens = {
  color: {
    primary: '#007392',
    secondary: '#2CB4F1',
    highlight: '#FDD704',
    heading: '#153243',
    surface: '#FFFFFF',
    surfaceMuted: '#F4F7F8',
    text: '#153243',
    textMuted: '#45616D',
    border: '#B8C6CB',
    focus: '#005FCC',
    success: '#0F766E',
    warning: '#8A5200',
    danger: '#B42318',
    onPrimary: '#FFFFFF',
    onHighlight: '#153243',
  },
  typography: {
    fontFamily: {
      sans: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    },
    fontSize: {
      xs: '0.78rem',
      sm: '0.85rem',
      bodySmall: '0.9rem',
      base: '1rem',
      lead: '1.4rem',
      display: '2.3rem',
    },
    fontWeight: {
      regular: 400,
      semibold: 700,
      strong: 750,
      bold: 800,
      black: 900,
    },
    lineHeight: {
      tight: 1.15,
      normal: 1.5,
    },
    letterSpacing: {
      label: '0.09em',
      code: '0.12em',
    },
  },
  spacing: {
    xs: '0.25rem',
    compact: '0.35rem',
    sm: '0.5rem',
    control: '0.65rem',
    md: '0.75rem',
    cozy: '0.8rem',
    field: '0.9rem',
    lg: '1rem',
    card: '1.25rem',
    shell: '1.4rem',
    xl: '1.5rem',
    wide: '2rem',
    xxl: '2.5rem',
  },
  radius: {
    sm: '0.35rem',
    md: '0.55rem',
    lg: '0.75rem',
    xl: '1rem',
    pill: '999px',
  },
  border: {
    width: '1px',
    subtle: '#D8E1E4',
    brand: 'rgb(0 115 146 / 18%)',
    danger: 'rgb(180 35 24 / 28%)',
  },
  shadow: {
    sm: '0 8px 24px rgb(21 50 67 / 6%)',
    md: '0 10px 24px rgb(21 50 67 / 9%)',
    lg: '0 16px 40px rgb(21 50 67 / 12%)',
  },
  state: {
    disabledOpacity: 0.6,
    primaryHover: '#005F79',
    success: { text: '#05603A', surface: '#E9F8F0' },
    pending: { text: '#075985', surface: '#E8F6FC' },
    warning: { text: '#7A4D00', surface: '#FFF6D6' },
    danger: { text: '#8D2118', surface: '#FFF1F0' },
    neutral: { text: '#334E5A', surface: '#EDF2F4' },
    secret: { text: '#102F3D', surface: '#EEF5F7' },
    sidebarNote: '#C8D8DE',
    backdrop: 'rgb(10 28 38 / 65%)',
    authAccent: 'rgb(44 180 241 / 18%)',
    authStart: '#EDF7F9',
    authMiddle: '#F8FAFC',
    authEnd: '#EEF4F6',
  },
} as const;

export const jrcCssVariables = {
  '--jrc-primary': jrcTokens.color.primary,
  '--jrc-secondary': jrcTokens.color.secondary,
  '--jrc-highlight': jrcTokens.color.highlight,
  '--jrc-heading': jrcTokens.color.heading,
  '--jrc-surface': jrcTokens.color.surface,
  '--jrc-surface-muted': jrcTokens.color.surfaceMuted,
  '--jrc-text': jrcTokens.color.text,
  '--jrc-text-muted': jrcTokens.color.textMuted,
  '--jrc-border': jrcTokens.color.border,
  '--jrc-focus': jrcTokens.color.focus,
  '--jrc-danger': jrcTokens.color.danger,
  '--jrc-on-primary': jrcTokens.color.onPrimary,
  '--jrc-on-highlight': jrcTokens.color.onHighlight,
  '--jrc-font-family-sans': jrcTokens.typography.fontFamily.sans,
  '--jrc-font-size-xs': jrcTokens.typography.fontSize.xs,
  '--jrc-font-size-sm': jrcTokens.typography.fontSize.sm,
  '--jrc-font-size-body-small': jrcTokens.typography.fontSize.bodySmall,
  '--jrc-font-size-base': jrcTokens.typography.fontSize.base,
  '--jrc-font-size-lead': jrcTokens.typography.fontSize.lead,
  '--jrc-font-size-display': jrcTokens.typography.fontSize.display,
  '--jrc-font-weight-regular': String(jrcTokens.typography.fontWeight.regular),
  '--jrc-font-weight-semibold': String(jrcTokens.typography.fontWeight.semibold),
  '--jrc-font-weight-strong': String(jrcTokens.typography.fontWeight.strong),
  '--jrc-font-weight-bold': String(jrcTokens.typography.fontWeight.bold),
  '--jrc-font-weight-black': String(jrcTokens.typography.fontWeight.black),
  '--jrc-line-height-tight': String(jrcTokens.typography.lineHeight.tight),
  '--jrc-line-height-normal': String(jrcTokens.typography.lineHeight.normal),
  '--jrc-letter-spacing-label': jrcTokens.typography.letterSpacing.label,
  '--jrc-letter-spacing-code': jrcTokens.typography.letterSpacing.code,
  '--jrc-space-xs': jrcTokens.spacing.xs,
  '--jrc-space-compact': jrcTokens.spacing.compact,
  '--jrc-space-sm': jrcTokens.spacing.sm,
  '--jrc-space-control': jrcTokens.spacing.control,
  '--jrc-space-md': jrcTokens.spacing.md,
  '--jrc-space-cozy': jrcTokens.spacing.cozy,
  '--jrc-space-field': jrcTokens.spacing.field,
  '--jrc-space-lg': jrcTokens.spacing.lg,
  '--jrc-space-card': jrcTokens.spacing.card,
  '--jrc-space-shell': jrcTokens.spacing.shell,
  '--jrc-space-xl': jrcTokens.spacing.xl,
  '--jrc-space-wide': jrcTokens.spacing.wide,
  '--jrc-space-xxl': jrcTokens.spacing.xxl,
  '--jrc-radius-sm': jrcTokens.radius.sm,
  '--jrc-radius-md': jrcTokens.radius.md,
  '--jrc-radius-lg': jrcTokens.radius.lg,
  '--jrc-radius-xl': jrcTokens.radius.xl,
  '--jrc-radius-pill': jrcTokens.radius.pill,
  '--jrc-border-width': jrcTokens.border.width,
  '--jrc-border-subtle': jrcTokens.border.subtle,
  '--jrc-border-brand': jrcTokens.border.brand,
  '--jrc-border-danger': jrcTokens.border.danger,
  '--jrc-shadow-sm': jrcTokens.shadow.sm,
  '--jrc-shadow-md': jrcTokens.shadow.md,
  '--jrc-shadow-lg': jrcTokens.shadow.lg,
  '--jrc-disabled-opacity': String(jrcTokens.state.disabledOpacity),
  '--jrc-primary-hover': jrcTokens.state.primaryHover,
  '--jrc-state-success-text': jrcTokens.state.success.text,
  '--jrc-state-success-surface': jrcTokens.state.success.surface,
  '--jrc-state-pending-text': jrcTokens.state.pending.text,
  '--jrc-state-pending-surface': jrcTokens.state.pending.surface,
  '--jrc-state-warning-text': jrcTokens.state.warning.text,
  '--jrc-state-warning-surface': jrcTokens.state.warning.surface,
  '--jrc-state-danger-text': jrcTokens.state.danger.text,
  '--jrc-state-danger-surface': jrcTokens.state.danger.surface,
  '--jrc-state-neutral-text': jrcTokens.state.neutral.text,
  '--jrc-state-neutral-surface': jrcTokens.state.neutral.surface,
  '--jrc-state-secret-text': jrcTokens.state.secret.text,
  '--jrc-state-secret-surface': jrcTokens.state.secret.surface,
  '--jrc-sidebar-note': jrcTokens.state.sidebarNote,
  '--jrc-backdrop': jrcTokens.state.backdrop,
  '--jrc-auth-accent': jrcTokens.state.authAccent,
  '--jrc-auth-start': jrcTokens.state.authStart,
  '--jrc-auth-middle': jrcTokens.state.authMiddle,
  '--jrc-auth-end': jrcTokens.state.authEnd,
} as const satisfies Record<`--jrc-${string}`, string>;

export type JrcCssVariables = typeof jrcCssVariables;
