import {expect,test} from '@playwright/test';
import {platformTestCredentials} from './platform-fixture.js';
import {expectNoAutomaticAccessibilityViolations} from './helpers.js';
test('administração JRC: senha, empresa, integração, limites e suporte auditado',async({page},testInfo)=>{
 const credentials=platformTestCredentials(testInfo.project.name);
 await page.goto('/jrc');await expect(page.getByRole('heading',{name:'Administração JRC'})).toBeVisible();
 await page.getByLabel('E-mail JRC').fill(credentials.email);await page.getByLabel('Senha',{exact:true}).fill(credentials.password);
 await expect(page.getByLabel('Código do autenticador')).toHaveCount(0);await page.getByRole('button',{name:'Entrar na administração'}).click();
 await expect(page.getByRole('heading',{name:'Visão geral',exact:true})).toBeVisible();
 await page.getByLabel('Motivo do atendimento').fill('Homologação SaaS com dados sintéticos');
 await page.getByRole('button',{name:'Cadastrar empresa'}).click();
 const name=`Empresa SaaS ${testInfo.project.name}`;
 await page.getByLabel('Nome da empresa').fill(name);await page.getByLabel('Identificador',{exact:true}).fill(`saas-${testInfo.project.name}`);
 await page.getByLabel('E-mail do responsável').fill(`owner-${testInfo.project.name}@example.test`);
 await page.getByLabel('Senha inicial do responsável').fill('synthetic-tenant-password');
 await page.getByRole('button',{name:'Salvar empresa'}).click();
 await expect(page.getByText('Empresa cadastrada com responsável e limites.')).toBeVisible();
 await page.getByRole('button',{name:`Abrir ${name}`}).click();
 await page.getByRole('tab',{name:'Usuários e acessos',exact:true}).click();
 const resetTrigger=page.getByRole('button',{name:`Redefinir senha de owner-${testInfo.project.name}@example.test`});
 await resetTrigger.click();
 let resetDialog=page.getByRole('dialog',{name:'Redefinir senha global'});
 await expect(resetDialog.getByRole('table',{name:'Todas as empresas vinculadas ao usuário'})).toContainText(name);
 await expect(resetDialog).toContainText('A senha é global');
 await expect(resetDialog.getByRole('button',{name:'Confirmar redefinição global'})).toBeDisabled();
 await resetDialog.getByLabel('Nova senha',{exact:true}).fill('synthetic-reset-password');
 await resetDialog.getByRole('button',{name:'Cancelar',exact:true}).click();
 await expect(resetDialog).toHaveCount(0);
 await expect(resetTrigger).toBeFocused();
 await resetTrigger.click();
 resetDialog=page.getByRole('dialog',{name:'Redefinir senha global'});
 await expect(resetDialog.getByLabel('Nova senha',{exact:true})).toHaveValue('');
 await resetDialog.getByRole('heading',{name:'Redefinir senha global'}).focus();
 await page.keyboard.press('Tab');
 await expect(resetDialog.getByRole('region',{name:'Vínculos do usuário'})).toBeFocused();
 await expectNoAutomaticAccessibilityViolations(page);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);
 await resetDialog.getByLabel('Confirme o e-mail do usuário').fill(`owner-${testInfo.project.name}@example.test`);
 await resetDialog.getByLabel('Nova senha',{exact:true}).fill('synthetic-reset-password');
 await resetDialog.getByLabel('Repita a nova senha',{exact:true}).fill('synthetic-reset-password');
 await resetDialog.getByRole('button',{name:'Confirmar redefinição global'}).click();
 await expect(page.getByRole('status')).toContainText('Senha redefinida.');
 await expect(resetDialog).toHaveCount(0);
 expect(await page.evaluate(()=>Object.values(localStorage).concat(Object.values(sessionStorage)).some(value=>value.includes('synthetic-reset-password')))).toBe(false);
 await page.getByRole('tab',{name:'JRC Conversas',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Central de atendimento — JRC Conversas / Chatwoot'})).toBeVisible();
 await expect(page.getByText(/aguardando configuração no servidor/)).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);
 await page.getByRole('tab',{name:'Plano e limites',exact:true}).click();
 await page.getByRole('combobox',{name:'Situação',exact:true}).selectOption('SUSPENDED');await page.getByRole('button',{name:'Salvar situação',exact:true}).click();
 await expect(page.getByText('Configuração da empresa atualizada e auditada.')).toBeVisible();
 await page.getByRole('tab',{name:'Intervenção administrativa',exact:true}).click();
 await page.getByRole('button',{name:'Registrar intervenção'}).click();await expect(page.getByText('Intervenção registrada na auditoria da empresa.')).toBeVisible();
 await expectNoAutomaticAccessibilityViolations(page);
 await page.screenshot({path:`test-results/saas-platform-${testInfo.project.name}.png`,fullPage:true});
 await page.goto('/jrc/grupos');
 await page.getByLabel('Nome do grupo',{exact:true}).fill(`Grupo sintético ${testInfo.project.name}`);
 await page.getByRole('button',{name:'Criar grupo',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('Grupo criado. Selecione as empresas.');
 await page.getByRole('checkbox',{name,exact:true}).check();
 await page.getByRole('button',{name:'Salvar empresas do grupo',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('Grupo atualizado. Os acessos das empresas foram preservados.');
 await page.getByLabel('Novo nome do grupo').fill(`Grupo renomeado ${testInfo.project.name}`);
 await page.getByRole('button',{name:'Renomear grupo',exact:true}).click();
 await expect(page.getByRole('status')).toHaveText('Nome do grupo atualizado. Empresas e acessos preservados.');
 await page.getByRole('button',{name:'Remover grupo',exact:true}).click();
 const removal=page.getByRole('dialog',{name:'Remover somente o grupo'});
 await expect(removal).toContainText(name);
 await expect(removal.getByRole('button',{name:'Confirmar remoção do grupo'})).toBeDisabled();
 await removal.getByLabel('Preservar as empresas e deixá-las sem grupo').check();
 await removal.getByRole('button',{name:'Confirmar remoção do grupo'}).click();
 await expect(page.getByRole('status')).toHaveText('Grupo removido. As empresas e seus dados foram preservados.');
 await page.goto('/jrc/empresas');
 await expect(page.getByRole('button',{name:`Abrir ${name}`})).toBeVisible();
 await page.getByRole('button',{name:'Sair da administração'}).click();await expect(page.getByRole('heading',{name:'Administração JRC'})).toBeVisible();
});
