import {expect,test} from '@playwright/test';
import {platformTestCredentials} from './platform-fixture.js';
import {expectNoAutomaticAccessibilityViolations} from './helpers.js';
test('administração JRC: senha, empresa, integração, limites e suporte auditado',async({page},testInfo)=>{
 const credentials=platformTestCredentials(testInfo.project.name);
 await page.goto('/jrc');await expect(page.getByRole('heading',{name:'Administração JRC'})).toBeVisible();
 await page.getByLabel('E-mail JRC').fill(credentials.email);await page.getByLabel('Senha',{exact:true}).fill(credentials.password);
 await expect(page.getByLabel('Código do autenticador')).toHaveCount(0);await page.getByRole('button',{name:'Entrar na administração'}).click();
 await expect(page.getByRole('heading',{name:'Visão geral',exact:true})).toBeVisible();
 await page.getByLabel('Motivo do atendimento').fill('Homologação SaaS com dados sintéticos');
 await page.getByRole('button',{name:'Cadastrar empresa'}).click();
 const name=`Empresa SaaS ${testInfo.project.name}`;
 await page.getByLabel('Nome da empresa').fill(name);await page.getByLabel('Identificador',{exact:true}).fill(`saas-${testInfo.project.name}`);
 await page.getByLabel('E-mail do responsável').fill(`owner-${testInfo.project.name}@example.test`);
 await page.getByLabel('Senha inicial do responsável').fill('synthetic-tenant-password');
 await page.getByRole('button',{name:'Salvar empresa'}).click();
 await expect(page.getByText('Empresa cadastrada com responsável e limites.')).toBeVisible();
 await page.getByRole('button',{name:`Abrir ${name}`}).click();
 await page.getByRole('tab',{name:'JRC Conversas',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Integração com o JRC Conversas'})).toBeVisible();
 await expect(page.getByText(/aguardando configuração no servidor/)).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);
 await page.getByRole('tab',{name:'Plano e limites',exact:true}).click();
 await page.getByRole('combobox',{name:'Situação',exact:true}).selectOption('SUSPENDED');await page.getByRole('button',{name:'Salvar situação e plano'}).click();
 await expect(page.getByText('Configuração da empresa atualizada e auditada.')).toBeVisible();
 await page.getByRole('tab',{name:'Suporte',exact:true}).click();
 await page.getByRole('button',{name:'Registrar atendimento de suporte'}).click();await expect(page.getByText('Atendimento registrado na auditoria da empresa.')).toBeVisible();
 await expectNoAutomaticAccessibilityViolations(page);
 await page.screenshot({path:`test-results/saas-platform-${testInfo.project.name}.png`,fullPage:true});
 await page.getByRole('button',{name:'Sair da administração'}).click();await expect(page.getByRole('heading',{name:'Administração JRC'})).toBeVisible();
});
