import {randomUUID} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {setTimeout as wait} from 'node:timers/promises';
import {Pool} from 'pg';
import {z} from 'zod';
import {withOrganizationTransaction} from '../db/tenant-transaction.js';
import {createOutboxDispatcher} from '../modules/automations/service.js';
import {createPostgresAutomationRepository,type OutboxRow} from '../modules/automations/repository.js';
import {createCredentialService,createCredentialVault} from '../modules/automation-integrations/credentials.js';
import {createAutomationSafeHttp} from '../modules/automation-integrations/safe-http.js';
import {executeReadOnlySql} from '../modules/automation-integrations/sql.js';
import {createAiExecutor,createOpenAiCompatibleAdapter,type AiOperation} from '../modules/automation-integrations/ai.js';
import {recordHeartbeat,workerInstanceId} from '../modules/observability/service.js';

const ioKinds=['IO_HTTP','IO_SQL','IO_CODE','IO_AI'] as const;
const render=(value:unknown,variables:Record<string,unknown>):unknown=>typeof value==='string'?value.replace(/\{\{\s*([a-zA-Z_][\w.-]*)\s*\}\}/g,(_,key:string)=>String(variables[key]??'')):Array.isArray(value)?value.map(item=>render(item,variables)):value&&typeof value==='object'?Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([key,child])=>[key,render(child,variables)])):value;
const object=(value:unknown)=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
const text=(value:unknown)=>typeof value==='string'?value:'';
export function loadAutomationIoWorkerConfig(environment:NodeJS.ProcessEnv){const databaseUrl=z.string().url().parse(environment.DATABASE_URL);if(new URL(databaseUrl).username!=='jrc_app')throw new Error('AUTOMATION_IO_WORKER_REQUIRES_APP_ROLE');return {databaseUrl,keyring:z.string().min(10).parse(environment.CREDENTIAL_VAULT_KEYS_JSON),sandboxUrl:z.string().url().parse(environment.AUTOMATION_SANDBOX_URL??'http://automation-sandbox:8080'),sandboxToken:z.string().min(32).parse(environment.AUTOMATION_SANDBOX_TOKEN),intervalMs:z.coerce.number().int().min(100).max(60000).default(1000).parse(environment.AUTOMATION_IO_WORKER_INTERVAL_MS)};}
export async function runAutomationIoWorker(environment:NodeJS.ProcessEnv=process.env,watch=false){const config=loadAutomationIoWorkerConfig(environment),pool=new Pool({connectionString:config.databaseUrl,max:4,connectionTimeoutMillis:5000,statement_timeout:35000});
 const instanceId=workerInstanceId();
 const repository=createPostgresAutomationRepository(),transact=<T>(org:string,work:Parameters<typeof withOrganizationTransaction<T>>[2])=>withOrganizationTransaction(pool,org,work),credentials=createCredentialService({transact,vault:createCredentialVault(config.keyring)}),safeHttp=createAutomationSafeHttp({});
 const audit=async(item:OutboxRow,outcome:string,started:number,credentialId?:string,detail:Record<string,unknown>={})=>transact(item.organizationId,tx=>tx.query(`insert into automation_io_audit(organization_id,execution_id,node_id,kind,credential_id,outcome,duration_ms,detail) values($1,$2,$3,$4,$5,$6,$7,$8)`,[item.organizationId,item.executionId,item.nodeId,item.kind,credentialId??null,outcome,Date.now()-started,JSON.stringify(detail)]).then(()=>undefined));
 const ai=createAiExecutor({resolveProvider:async(org,id)=>{const resolved=await credentials.resolve(org,id),secret=resolved.secret,baseUrl=text(secret.baseUrl),apiKey=text(secret.apiKey),provider=text(secret.provider)||'openai-compatible';if(resolved.type!=='AI_PROVIDER'||!baseUrl||!apiKey)throw new Error('AUTOMATION_AI_CREDENTIAL_INVALID');return createOpenAiCompatibleAdapter({baseUrl,apiKey,provider,request:safeHttp});},audit:async event=>transact(event.organizationId,tx=>tx.query(`insert into automation_io_audit(organization_id,execution_id,node_id,kind,outcome,duration_ms,detail) values($1,$2,$3,'IO_AI',$4,$5,$6)`,[event.organizationId,event.executionId??null,event.nodeId,event.outcome,event.durationMs,JSON.stringify({provider:event.provider,model:event.model,usage:event.usage})]).then(()=>undefined))});
 const outbox=createOutboxDispatcher({transact,repository},{dispatch:async item=>{const started=Date.now(),payload=object(render(item.payload,object(item.payload.variables))),credentialId=text(payload.credentialId)||undefined;try{
   let output:unknown,outcome='success';
   if(item.kind==='IO_HTTP'){const resolved=credentialId?await credentials.resolve(item.organizationId,credentialId):null,headers={...object(payload.headers)} as Record<string,string>;if(resolved){const secret=resolved.secret;if(resolved.type==='BEARER')headers.authorization=`Bearer ${text(secret.token)}`;else if(resolved.type==='BASIC')headers.authorization=`Basic ${Buffer.from(`${text(secret.username)}:${text(secret.password)}`).toString('base64')}`;else if(resolved.type==='HTTP_HEADER')headers[text(secret.name)]=text(secret.value);else Object.assign(headers,object(secret.headers));}const response=await safeHttp({method:(text(payload.method)||'GET') as 'GET',url:text(payload.url),headers,...(payload.body===undefined?{}:{body:typeof payload.body==='string'?payload.body:JSON.stringify(payload.body)}),timeoutMs:Number(payload.timeoutMs??15000),retryAttempts:Number(payload.retryAttempts??0)});output={status:response.status,headers:response.headers,body:response.body};outcome=response.outcome;}
   else if(item.kind==='IO_SQL'){if(!credentialId)throw new Error('AUTOMATION_CREDENTIAL_REQUIRED');const resolved=await credentials.resolve(item.organizationId,credentialId),connectionString=text(resolved.secret.connectionString);output=await executeReadOnlySql({type:resolved.type as 'POSTGRES'|'MYSQL',connectionString,query:text(payload.query),parameters:Array.isArray(payload.parameters)?payload.parameters:[],timeoutMs:Number(payload.timeoutMs??5000),maxRows:Number(payload.maxRows??100)});}
   else if(item.kind==='IO_CODE'){const response=await fetch(config.sandboxUrl,{method:'POST',headers:{authorization:`Bearer ${config.sandboxToken}`,'content-type':'application/json'},body:JSON.stringify({code:text(payload.code),input:payload.input??payload.variables}),signal:AbortSignal.timeout(4000)}),result=await response.json() as {ok?:boolean;value?:unknown;error?:string};if(!response.ok||!result.ok)throw new Error(result.error??'AUTOMATION_SANDBOX_FAILED');output=result.value;}
   else {if(!credentialId)throw new Error('AUTOMATION_CREDENTIAL_REQUIRED');const operation=text(payload.nodeType).replace('ai-','') as AiOperation,result=await ai({organizationId:item.organizationId,executionId:item.executionId,nodeId:item.nodeId,credentialId,operation,model:text(payload.model),content:text(payload.content),schema:object(payload.schema),requestedTools:Array.isArray(payload.tools)?payload.tools.map(String):[],allowedTools:Array.isArray(payload.allowedTools)?payload.allowedTools.map(String):[]});output=result.output;}
   if(item.kind!=='IO_AI')await audit(item,outcome,started,credentialId,{status:'completed'});return {kind:'SENT' as const,remoteReference:`io:${item.id}`,resumePayload:{outcome,output}};
  }catch(error){const code=error instanceof Error?error.message.slice(0,120):'AUTOMATION_IO_FAILED',outcome=code.includes('TIMEOUT')||code.includes('aborted')?'timeout':item.kind==='IO_HTTP'?'unknown':'error';if(item.kind!=='IO_AI')await audit(item,outcome,started,credentialId,{error:code});return {kind:'FAILED' as const,error:code,resumePayload:{outcome,output:{error:code}}};}}},[...ioKinds]);
 const abort=new AbortController(),stop=()=>abort.abort();process.once('SIGINT',stop);process.once('SIGTERM',stop);try{do{const organizations=(await pool.query<{organization_id:string}>('select * from operational_worker_organizations(null,1000)')).rows.map(row=>row.organization_id);for(const org of organizations){if(abort.signal.aborted)break;await transact(org,tx=>recordHeartbeat(tx,org,'AUTOMATION_IO_WORKER',instanceId));await outbox.runOnce(org);}if(watch&&!abort.signal.aborted)await wait(config.intervalMs,undefined,{signal:abort.signal}).catch(()=>undefined);}while(watch&&!abort.signal.aborted);}finally{process.off('SIGINT',stop);process.off('SIGTERM',stop);await pool.end();}}
if(process.argv[1]&&pathToFileURL(process.argv[1]).href===import.meta.url)runAutomationIoWorker(process.env,process.argv.includes('--watch')).catch(()=>{process.stderr.write('AUTOMATION_IO_WORKER_FAILED\n');process.exitCode=1;});
