import { useEffect,useState,type FormEvent } from 'react';
import { Link,Navigate,useLocation,useNavigate,useParams } from 'react-router';
import { welcomeFlow,type AutomationDefinitionV1,type AutomationGraphV1 } from '@jrc/contracts';
import { ApiClientError } from '../api/client.js';
import { useApiClient,useSession } from '../auth/SessionProvider.js';
import { FlowCanvas } from '../flows/FlowCanvas.js';
import { createAutomation,getAutomation,listAutomationNodes,listAutomations,listExecutions,listVersions,saveAutomation,type AutomationExecution,type AutomationNodeCatalogItem } from '../automations/api.js';
import '../flows/flows.css';import '../automations/studio.css';

const errorMessage=(error:unknown)=>error instanceof ApiClientError?`${error.message}${error.requestId?` Solicitação: ${error.requestId}`:''}`:'Não foi possível concluir. Tente novamente.';
const statusLabel=(status:string)=>({DRAFT:'Rascunho',PUBLISHED:'Publicada',ARCHIVED:'Arquivada',QUEUED:'Na fila',RUNNING:'Executando',WAITING:'Aguardando',HANDOFF:'Atendimento humano',COMPLETED:'Concluída',FAILED:'Falhou',CANCELED:'Cancelada',UNKNOWN:'Requer reconciliação'}[status]??status);
const defaultGraph=()=>welcomeFlow() as AutomationGraphV1;

export function AutomationsPage(){const client=useApiClient(),{session}=useSession(),[items,setItems]=useState<AutomationDefinitionV1[]>([]),[enabled,setEnabled]=useState<boolean|null>(null),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();void Promise.all([client.request<{enabled:boolean}>('/v1/automations/status',{signal:controller.signal}),listAutomations(client)]).then(([status,list])=>{if(!controller.signal.aborted){setEnabled(status.enabled);setItems(list);}}).catch(reason=>{if(!controller.signal.aborted)setError(errorMessage(reason));});return()=>controller.abort();},[client]);
 if(enabled===false)return <section className="automation-page"><h1>Automações</h1><p>O Automation Runtime v2 está desativado para rollback. Os Flows legados continuam disponíveis.</p><Link to="/legacy/flows">Abrir JRC Flows legado</Link></section>;
 return <section className="automation-page"><header className="automation-page-header"><div><span>AUTOMAÇÃO</span><h1>Automações</h1><p>Crie, publique e acompanhe chatbots versionados.</p></div>{session&&['OWNER','ADMIN'].includes(session.activeOrganization.role)&&<Link className="flows-primary automation-link-button" to="/automations/new">Nova automação</Link>}</header>{error&&<p role="alert" className="flows-alert flows-alert--error">{error}</p>}{enabled===null&&!error?<p>Carregando…</p>:items.length?<div className="automation-cards">{items.map(item=><article key={item.id}><span className="flows-badge">{statusLabel(item.lifecycleStatus)}</span><h2>{item.name}</h2><p>Rascunho r{item.draft.revision} · ativa {item.activeVersion?`v${item.activeVersion}`:'não publicada'}</p><div className="flows-actions"><Link to={`/automations/${item.id}/edit`}>Editar</Link><Link to={`/automations/${item.id}/executions`}>Execuções</Link></div></article>)}</div>:enabled&&<div className="flows-empty"><h2>Crie sua primeira automação</h2><p>Comece com mensagem recebida, resposta e encerramento.</p></div>}</section>;
}

type ImportReport={summary:{total:number;exact:number;partial:number;unsupported:number;manualReviewRequired:boolean};nodes:Array<{sourceId:string;sourceType:string;classification:string;targetType:string|null;notes:string[]}>;warnings:string[]};
export function NewAutomationPage(){const client=useApiClient(),navigate=useNavigate(),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[source,setSource]=useState<'JRC'|'N8N'|'TYPEBOT'>('N8N'),[report,setReport]=useState<ImportReport|null>(null);async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const item=await createAutomation(client,name,defaultGraph());navigate(`/automations/${item.id}/edit`,{replace:true});}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 async function importFile(file:File){setBusy(true);setError('');try{const imported=await client.request<{name:string;graph:AutomationGraphV1;report:ImportReport}>('/v1/automation-imports',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({source,content:await file.text()})});setReport(imported.report);const item=await createAutomation(client,imported.name,imported.graph);navigate(`/automations/${item.id}/edit`,{replace:true,state:{importReport:imported.report}});}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 return <section className="automation-page automation-narrow"><Link to="/automations">← Voltar</Link><h1>Nova automação</h1><form onSubmit={event=>void submit(event)}><label>Nome<input autoFocus required maxLength={120} value={name} onChange={event=>setName(event.target.value)}/></label>{error&&<p role="alert" className="flows-alert flows-alert--error">{error}</p>}<button className="flows-primary" disabled={busy||!name.trim()}>Criar e abrir editor</button></form><hr/><h2>Importar automação</h2><p>Converte JSON JRC, n8n ou Typebot em rascunho. Credenciais são removidas e incompatibilidades ficam explícitas.</p><label>Origem<select value={source} onChange={event=>setSource(event.target.value as typeof source)}><option value="JRC">JRC</option><option value="N8N">n8n</option><option value="TYPEBOT">Typebot</option></select></label><label className="automation-link-button">Selecionar JSON<input hidden type="file" accept="application/json,.json" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void importFile(file);}}/></label>{report&&<p>{report.summary.exact} exatos · {report.summary.partial} parciais · {report.summary.unsupported} incompatíveis</p>}</section>;
}

type Simulation={status:string;state:{variables:Record<string,string>};effects:Array<{kind:string;payload:Record<string,unknown>}>;trace:Array<{nodeId:string;label:string;type:string}>};
export function AutomationEditorPage(){const {id=''}=useParams(),location=useLocation(),client=useApiClient(),{session}=useSession(),[item,setItem]=useState<AutomationDefinitionV1|null>(null),[catalog,setCatalog]=useState<AutomationNodeCatalogItem[]>([]),[baseline,setBaseline]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[validation,setValidation]=useState<string[]|null>(null),[testText,setTestText]=useState('Olá'),[simulation,setSimulation]=useState<Simulation|null>(null),[drawer,setDrawer]=useState('Input');
 const editable=Boolean(session&&['OWNER','ADMIN'].includes(session.activeOrganization.role)),draftKey=`jrc-automation-draft:${session?.activeOrganization.id}:${id}`;
 useEffect(()=>{const controller=new AbortController();void Promise.all([getAutomation(client,id),listAutomationNodes(client)]).then(([automation,nodes])=>{if(controller.signal.aborted)return;const cached=sessionStorage.getItem(draftKey);let restored=automation;if(cached)try{const value=JSON.parse(cached) as {revision:number;name:string;graph:AutomationGraphV1};if(value.revision===automation.draft.revision)restored={...automation,name:value.name,draft:{...automation.draft,graph:value.graph}};}catch{}setItem(restored);setBaseline(JSON.stringify({name:automation.name,graph:automation.draft.graph}));setCatalog(nodes);}).catch(reason=>{if(!controller.signal.aborted)setError(errorMessage(reason));});return()=>controller.abort();},[client,id,draftKey]);
 const dirty=Boolean(item&&JSON.stringify({name:item.name,graph:item.draft.graph})!==baseline),summary=item?`${item.draft.graph.nodes.length} blocos · ${item.draft.graph.edges.length} conexões`:'';
 useEffect(()=>{if(item&&dirty)sessionStorage.setItem(draftKey,JSON.stringify({revision:item.draft.revision,name:item.name,graph:item.draft.graph}));},[item,dirty,draftKey]);
 useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 async function action(work:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await work();}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 async function save(){if(!item)return;await action(async()=>{const saved=await saveAutomation(client,item);setItem(saved);setBaseline(JSON.stringify({name:saved.name,graph:saved.draft.graph}));sessionStorage.removeItem(draftKey);setNotice('Rascunho salvo.');});}
 async function validate(){if(!item)return;await action(async()=>{const result=await client.request<{valid:boolean;errors:string[]}>(`/v1/automations/${id}/validate`,{method:'POST',body:'{}'});setValidation(result.errors);setDrawer('Errors');setNotice(result.valid?'Automação válida.':'Revise os erros encontrados.');});}
 async function simulate(){if(!item)return;await action(async()=>{const result=await client.request<Simulation>(`/v1/automations/${id}/simulate`,{method:'POST',body:JSON.stringify({text:testText})});setSimulation(result);setDrawer('Output');});}
 async function publish(){if(!item)return;await action(async()=>{const result=await client.request<{version:number}>(`/v1/automations/${id}/publish`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({revision:item.draft.revision})});const refreshed=await getAutomation(client,id);setItem(refreshed);setBaseline(JSON.stringify({name:refreshed.name,graph:refreshed.draft.graph}));setNotice(`Versão ${result.version} publicada.`);});}
 if(!item)return <section className="automation-page"><h1>Automation Studio</h1><p>{error||'Carregando editor…'}</p></section>;
 return <section className="automation-page automation-editor"><header className="automation-editor-header"><Link to="/automations">← Voltar</Link><label>Nome<input aria-label="Nome da automação" disabled={!editable} value={item.name} onChange={event=>setItem({...item,name:event.target.value})}/></label><span className="flows-badge">{statusLabel(item.lifecycleStatus)} · {item.activeVersion?`v${item.activeVersion}`:'sem versão'}</span><div className="flows-actions"><button disabled={!editable||busy||!dirty} onClick={()=>void save()}>Salvar</button><button disabled={busy||dirty} onClick={()=>void validate()}>Validar</button><button disabled={busy||dirty} onClick={()=>void simulate()}>Testar</button><button className="flows-primary" disabled={!editable||busy||dirty} onClick={()=>void publish()}>Publicar</button><Link to={`/automations/${id}/versions`}>Histórico</Link></div></header>
  <div className="automation-change-summary" aria-live="polite">{summary}{dirty?' · alterações locais preservadas neste navegador':' · rascunho salvo'}</div>{error&&<p role="alert" className="flows-alert flows-alert--error">{error}</p>}{notice&&<p className="flows-alert">{notice}</p>}{(location.state as {importReport?:ImportReport}|null)?.importReport&&<details open className="flows-alert"><summary>Relatório da importação</summary><pre>{JSON.stringify((location.state as {importReport:ImportReport}).importReport,null,2)}</pre></details>}
  <FlowCanvas graph={item.draft.graph} editable={editable} catalog={catalog} onChange={graph=>{setItem({...item,draft:{...item.draft,graph}});setValidation(null);}}/>
  <section className="automation-drawer"><nav aria-label="Detalhes do teste">{['Input','Output','Variables','Execution','Logs','Errors'].map(tab=><button key={tab} aria-current={drawer===tab||undefined} onClick={()=>setDrawer(tab)}>{tab}</button>)}</nav><div role="region" aria-live="polite">{drawer==='Input'&&<label>Mensagem de teste<input value={testText} maxLength={4096} onChange={event=>setTestText(event.target.value)}/></label>}{drawer==='Output'&&<pre>{JSON.stringify(simulation?.effects??[],null,2)}</pre>}{drawer==='Variables'&&<pre>{JSON.stringify(simulation?.state.variables??{},null,2)}</pre>}{drawer==='Execution'&&<p>{simulation?statusLabel(simulation.status):'Execute um teste para ver o estado.'}</p>}{drawer==='Logs'&&<ol>{simulation?.trace.map((step,index)=><li key={`${step.nodeId}-${index}`}>{step.label} · {step.type}</li>)}</ol>}{drawer==='Errors'&&(validation?.length?<ul>{validation.map(problem=><li key={problem}>{problem}</li>)}</ul>:<p>Nenhum erro local.</p>)}</div></section>
 </section>;
}

export function AutomationVersionsPage(){const {id=''}=useParams(),client=useApiClient(),[name,setName]=useState(''),[versions,setVersions]=useState<Array<{version:number;checksum:string;publishedAt:string;graph:AutomationGraphV1}>>([]),[error,setError]=useState('');useEffect(()=>{void Promise.all([getAutomation(client,id),listVersions(client,id)]).then(([item,list])=>{setName(item.name);setVersions(list);}).catch(reason=>setError(errorMessage(reason)));},[client,id]);return <section className="automation-page"><Link to={`/automations/${id}/edit`}>← Editor</Link><h1>Versões · {name}</h1>{error&&<p role="alert">{error}</p>}{versions.map((version,index)=><details key={version.version}><summary>v{version.version} · {new Date(version.publishedAt).toLocaleString('pt-BR')} · {version.graph.nodes.length} blocos</summary><p>Checksum: <code>{version.checksum}</code></p>{index===0?<p>Versão ativa mais recente.</p>:<p>Versão imutável preservada para execuções antigas.</p>}</details>)}</section>}

export function AutomationExecutionsPage(){const {id}=useParams(),client=useApiClient(),[items,setItems]=useState<AutomationExecution[]>([]),[error,setError]=useState('');useEffect(()=>{void listExecutions(client,id).then(setItems).catch(reason=>setError(errorMessage(reason)));},[client,id]);return <section className="automation-page"><header className="automation-page-header"><div><h1>Execuções</h1><p>Timeline das automações com versão e correlação.</p></div></header>{error&&<p role="alert">{error}</p>}{items.length?<div className="automation-execution-list">{items.map(item=><Link key={item.id} to={`/automation-executions/${item.id}`}><span className={`execution-state execution-state--${item.status.toLowerCase()}`}>{statusLabel(item.status)}</span><strong>v{item.version}</strong><span>{new Date(item.startedAt).toLocaleString('pt-BR')}</span><code>{item.correlationId}</code></Link>)}</div>:<p className="flows-empty">Nenhuma execução encontrada.</p>}</section>}

export function AutomationExecutionDetailPage(){const {id=''}=useParams(),client=useApiClient(),{session}=useSession(),[item,setItem]=useState<AutomationExecution|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),editable=Boolean(session&&['OWNER','ADMIN'].includes(session.activeOrganization.role));
 const load=()=>client.request<AutomationExecution>(`/v1/executions/${id}`).then(setItem);useEffect(()=>{void load().catch(reason=>setError(errorMessage(reason)));},[client,id]);
 async function reconcile(outboxId:string,outcome:'CONFIRMED_SENT'|'CONFIRMED_NOT_SENT'|'UNRESOLVED'){setBusy(true);setError('');setNotice('');try{await client.request(`/v1/executions/${id}/reconcile`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({outboxId,outcome,evidenceCode:'OPERATOR_PROVIDER_CHECK'})});await load();setNotice(outcome==='CONFIRMED_NOT_SENT'?'Efeito confirmado como não enviado e liberado para retry seguro.':'Reconciliação registrada sem reenvio automático.');}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}}
 if(!item)return <section className="automation-page"><h1>Execução</h1><p>{error||'Carregando…'}</p></section>;
 return <section className="automation-page"><Link to="/automation-executions">← Execuções</Link><h1>Execução {item.id.slice(0,8)}</h1>{error?<p role="alert">{error}</p>:null}{notice?<p className="flows-alert">{notice}</p>:null}<dl className="execution-metadata"><div><dt>Status</dt><dd>{statusLabel(item.status)}</dd></div><div><dt>Automação / versão</dt><dd><code>{item.automationId}</code> · v{item.version}</dd></div><div><dt>Canal</dt><dd><code>{item.channelId}</code></dd></div><div><dt>Correlation ID</dt><dd><code>{item.correlationId}</code></dd></div><div><dt>Conversa</dt><dd><code>{item.conversationRef??'—'}</code></dd></div><div><dt>Contato</dt><dd><code>{item.contactRef??'—'}</code></dd></div><div><dt>Duração</dt><dd>{item.durationMs??0} ms</dd></div><div><dt>Erro</dt><dd>{item.errorCode??'—'}</dd></div></dl>
 <h2>Timeline por nó</h2><ol className="execution-timeline">{item.nodes?.map(node=><li key={node.id}><span /><div><strong>{node.nodeId}</strong><small>{statusLabel(node.status)} · tentativa {node.attempt} · {node.durationMs===null?'em andamento':`${node.durationMs} ms`}</small>{node.errorCode?<p role="alert">Erro seguro: {node.errorCode}</p>:null}<details><summary>Input e output redigidos</summary><pre>{JSON.stringify({input:node.input,output:node.output},null,2)}</pre></details></div></li>)}</ol>
 <h2>Outbox e efeitos externos</h2>{item.outbox?.length?<div className="table-scroll"><table className="broker-table"><thead><tr><th>Nó</th><th>Efeito</th><th>Estado</th><th>Tentativas</th><th>Referência</th><th>Reconciliação</th></tr></thead><tbody>{item.outbox.map(effect=><tr key={effect.id}><td>{effect.nodeId}</td><td>{effect.kind}</td><td>{effect.status}</td><td>{effect.attempts}</td><td><code>{effect.remoteReference??'—'}</code></td><td>{effect.status==='UNKNOWN'&&editable?<div className="flows-actions"><button disabled={busy} onClick={()=>void reconcile(effect.id,'CONFIRMED_SENT')}>Confirmar envio</button><button disabled={busy} onClick={()=>void reconcile(effect.id,'CONFIRMED_NOT_SENT')}>Confirmar não enviado</button><button disabled={busy} onClick={()=>void reconcile(effect.id,'UNRESOLVED')}>Manter incerto</button></div>:'—'}</td></tr>)}</tbody></table></div>:<p>Nenhum efeito externo registrado.</p>}</section>}

export function FlowsCompatibilityRoute(){const client=useApiClient(),[enabled,setEnabled]=useState<boolean|null>(null);useEffect(()=>{void client.request<{enabled:boolean}>('/v1/automations/status').then(value=>setEnabled(value.enabled)).catch(()=>setEnabled(false));},[client]);if(enabled===null)return <p>Carregando…</p>;return enabled?<Navigate replace to="/automations"/>:<Navigate replace to="/legacy/flows"/>;}
