import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Link,useParams} from 'react-router';
import type {AutomationBindingV1,AutomationDefinitionV1,ChannelV1,ConnectionAction} from '@jrc/contracts';
import {useApiClient,useSession} from '../auth/SessionProvider.js';
import {ApiClientError} from '../api/client.js';
import {listAutomations} from '../automations/api.js';
import {bindChannelAutomation,bindChannelDestination,disconnectChannel,getChannel,getChannelAutomation,pairChannel,patchChannel,reconnectChannel,refreshChannelStatus} from '../channels/api.js';
import {statusLabel} from './Channels.js';
const failures:Record<string,string>={
 CHANNEL_DISCONNECT_REQUIRED:'Desconecte o WhatsApp e confirme o status antes de arquivar.',CHANNEL_HAS_PENDING_WORK:'Há envios ou operações pendentes. Conclua ou reconcilie antes de arquivar.',
 CHANNEL_UNLINK_REQUIRED:'Desvincule a automação e pause o atendimento antes de arquivar.',CHANNEL_ARCHIVED:'Restaure esta caixa antes de operar.',
 CHATWOOT_ACCOUNT_NOT_CONFIGURED:'Configure primeiro a conta da central em JRC Conversas / Chatwoot.',CHATWOOT_ACCOUNT_NOT_READY:'Confira a conta e a credencial da central de atendimento.',
 INTEGRATION_HAS_HISTORY:'O vínculo possui histórico. Mantenha-o pausado para preservar mensagens e auditoria.',
 AUTOMATION_BINDING_CHANGED:'O vínculo mudou. Atualize a página antes de tentar novamente.',
};
export function ChannelDetailPage(){
 const {id=''}=useParams(),client=useApiClient(),{session}=useSession();
 const [channel,setChannel]=useState<ChannelV1|null>(null),[action,setAction]=useState<ConnectionAction|null>(null),[binding,setBinding]=useState<AutomationBindingV1|null>(null);
 const [automations,setAutomations]=useState<AutomationDefinitionV1[]>([]),[automationId,setAutomationId]=useState(''),[displayName,setDisplayName]=useState(''),[destination,setDestination]=useState('');
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());const pending=useRef(false);
 const canManage=Boolean(session&&['OWNER','ADMIN'].includes(session.activeOrganization.role)),canPair=Boolean(session&&session.activeOrganization.role!=='VIEWER'),archived=Boolean(channel?.archivedAt);
 async function load(){const value=await getChannel(client,id);setChannel(value);setDisplayName(value.identity.displayName??'');const linked=await getChannelAutomation(client,id);setBinding(linked.binding);setAutomationId(linked.binding?.automationId??'');}
 useEffect(()=>{let live=true;void getChannel(client,id).then(value=>{if(live){setChannel(value);setDisplayName(value.identity.displayName??'');}}).catch(()=>{if(live)setError('Não foi possível carregar a caixa.');});
 void getChannelAutomation(client,id).then(value=>{if(live){setBinding(value.binding);setAutomationId(value.binding?.automationId??'');}}).catch(()=>{});
 void listAutomations(client).then(value=>{if(live)setAutomations(value.filter(item=>item.activeVersion!==null&&item.lifecycleStatus!=='ARCHIVED'));}).catch(()=>{});return()=>{live=false;};},[client,id]);
 useEffect(()=>{if(!action||action.type==='NONE')return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[action]);
 const expiresAt=action&&'expiresAt' in action?new Date(action.expiresAt).getTime():0,expired=Boolean(expiresAt&&expiresAt<=now);
 useEffect(()=>{if(!action||action.type==='NONE'||expired||archived)return;let live=true;const timer=setInterval(()=>{void refreshChannelStatus(client,id).then(value=>{if(live){setChannel(value);if(value.transportStatus==='CONNECTED'){setAction(null);setNotice('WhatsApp conectado. Agora confira o vínculo de atendimento e a automação.');}}}).catch(()=>{if(live)setError('Não foi possível atualizar o pareamento. Use Atualizar status.');});},4000);return()=>{live=false;clearInterval(timer);};},[action,expired,archived,client,id]);
 async function run(work:()=>Promise<void>,success=''){if(pending.current)return;pending.current=true;setBusy(true);setError('');setNotice('');try{await work();if(success)setNotice(success);}catch(reason){setError(reason instanceof ApiClientError?(failures[reason.code??'']??reason.message):'Não foi possível concluir. Atualize e tente novamente.');}finally{pending.current=false;setBusy(false);}}
 async function pair(reconnect=false){await run(async()=>{const result=await(reconnect?reconnectChannel:pairChannel)(client,id,crypto.randomUUID());setNow(Date.now());setAction(result.action);setChannel(await getChannel(client,id));if(result.action.type==='NONE')setNotice(result.channel.transportStatus==='CONNECTED'?'WhatsApp já conectado.':'Solicitação em processamento. Atualize o status e solicite o QR novamente em instantes.');});}
 async function disconnect(){if(!window.confirm('Desconectar este WhatsApp? Será necessário parear novamente. O histórico será preservado.'))return;await run(async()=>{const result=await disconnectChannel(client,id,crypto.randomUUID());setChannel(await getChannel(client,id));setAction(null);setNotice(result.pending?'Desconexão em processamento. Atualize o status.':'WhatsApp desconectado.');});}
 async function rename(event:FormEvent){event.preventDefault();await run(async()=>{setChannel(await patchChannel(client,id,{displayName:displayName.trim()}));},'Nome atualizado.');}
 async function bind(event:FormEvent){event.preventDefault();await run(async()=>{setChannel(await bindChannelDestination(client,id,{name:destination.trim(),replaceExistingWebhook:false}));},'Caixa vinculada. Confira a entrega no sistema de atendimento.');}
 async function bindAutomation(event:FormEvent){event.preventDefault();await run(async()=>{await bindChannelAutomation(client,id,{automationId});await load();},'Automação vinculada. Novas mensagens usarão esta versão.');}
 async function changeBinding(status:'ACTIVE'|'PAUSED'|'DISABLED'){if(!binding)return;if(!window.confirm(status==='DISABLED'?'Desvincular a automação? Novas mensagens não iniciarão este chatbot. Execuções já iniciadas continuam e podem ser canceladas em Execuções.':'Alterar recebimento de novas mensagens pelo chatbot? Execuções iniciadas continuam.'))return;await run(async()=>{await client.request(`/v1/automations/${binding.automationId}/bindings/${binding.id}`,{method:'PATCH',body:JSON.stringify({status,revision:binding.revision})});await load();},'Vínculo atualizado.');}
 async function destinationState(){if(!channel?.destination)return;const enabled=channel.humanStatus!=='READY';await run(async()=>{await client.request(`/v1/integrations/chatwoot/connections/${channel.destination!.integrationId}`,{method:'PATCH',body:JSON.stringify({enabled})});await load();},enabled?'Atendimento retomado.':'Atendimento pausado. Entregas pendentes foram preservadas.');}
 async function archive(){if(!window.confirm(archived?'Restaurar esta caixa? A conexão e os vínculos não serão ativados automaticamente.':'Arquivar este cadastro? Desconecte o WhatsApp, desvincule a automação e pause o atendimento antes. O histórico será preservado.'))return;await run(async()=>{await client.request(`/v1/channels/${id}/archive`,{method:'POST',body:JSON.stringify({archived:!archived})});await load();},archived?'Cadastro restaurado.':'Cadastro arquivado.');}
 return <section><Link className="back-link" to="/channels">← Caixas de entrada</Link>{error&&<p role="alert" className="notice notice--error">{error}</p>}{notice&&<p role="status" className="notice notice--success">{notice}</p>}
 {!channel?<p>Carregando caixa…</p>:<><p className="eyebrow">{channel.provider==='QR'?'WhatsApp por QR Code':'WhatsApp oficial Meta'}</p><h1>{channel.identity.displayName??'Caixa WhatsApp'}</h1>
 {archived&&<p className="notice">Cadastro arquivado. O histórico está preservado.</p>}
 <div className="metric-grid"><div className="metric"><small>WhatsApp</small><strong>{statusLabel[channel.transportStatus]}</strong><span>Número: {channel.identity.maskedAddress??'Ainda não identificado'}</span></div><div className="metric"><small>Automação JRC</small><strong>{channel.automationName??'Nenhuma selecionada'}</strong><span>{statusLabel[channel.automationStatus]}</span></div><div className="metric"><small>JRC Conversas / Chatwoot</small><strong>{channel.destination?.name??'Sem vínculo'}</strong><span>{statusLabel[channel.humanStatus]}</span></div></div>
 {!archived&&<><section className="panel"><h2>1. Conectar o WhatsApp</h2><div className="button-row"><button className="button button--secondary" disabled={busy} onClick={()=>void run(async()=>{setChannel(await refreshChannelStatus(client,id));},'Status atualizado.')}>Atualizar status</button>{channel.provider==='QR'&&canPair&&<><button className="button button--secondary" disabled={busy} onClick={()=>void pair(true)}>Reconectar</button>{channel.transportStatus!=='DISCONNECTED'&&<button className="button button--danger" disabled={busy} onClick={()=>void disconnect()}>Desconectar</button>}</>}</div>
 {channel.provider==='QR'&&canPair&&channel.transportStatus!=='CONNECTED'&&<><p>No celular, abra WhatsApp → Dispositivos conectados → Conectar dispositivo.</p><button className="button button--primary" disabled={busy} onClick={()=>void pair()}>Gerar QR Code</button>
 {expired?<p role="status">QR ou código expirado. Gere outro para continuar.</p>:action?.type==='QR_CODE'?<><img className="channel-qr" src={action.encoding==='BASE64'?'data:image/png;base64,'+action.value:action.value} alt="QR Code para conectar o WhatsApp"/><p>Expira em {Math.max(0,Math.ceil((expiresAt-now)/1000))} segundos.</p></>:action?.type==='PAIRING_CODE'?<p>Código de pareamento: <strong>{action.code}</strong></p>:null}</>}
 {channel.provider==='META'&&<p>A conexão oficial depende da autorização dos ativos no cadastro da Meta. <Link to="/channels/meta/connect">Abrir configuração oficial</Link></p>}</section>
 {channel.provider==='QR'&&canManage&&<form className="panel form-grid" onSubmit={event=>void rename(event)}><h2>Identificação</h2><label>Nome da caixa<input value={displayName} onChange={event=>setDisplayName(event.target.value)} required maxLength={100}/></label><div className="button-row"><button className="button button--primary" disabled={busy||!displayName.trim()}>Salvar nome</button><button className="button button--secondary" type="button" disabled={busy} onClick={()=>setDisplayName(channel.identity.displayName??'')}>Cancelar edição</button></div></form>}
 <section className="panel"><h2>2. Conectar a central de atendimento</h2><p>Escolha JRC Conversas ou uma instalação Chatwoot autorizada. O Broker encaminha mensagens e as respostas públicas dos atendentes.</p><Link to="/integracoes">Configurar conta, destino e caixas existentes</Link>
 {channel.destination?<><p>Caixa: <strong>{channel.destination.name}</strong> · {channel.destination.inboxId??'em configuração'}</p>{canManage&&<button className="button button--secondary" disabled={busy} onClick={()=>void destinationState()}>{channel.humanStatus==='READY'?'Pausar atendimento':'Retomar atendimento'}</button>}</>:canManage&&<form className="form-grid" onSubmit={event=>void bind(event)}><label>Nome da nova caixa na central<input value={destination} onChange={event=>setDestination(event.target.value)} required maxLength={120}/></label><button className="button button--primary" disabled={busy||!destination.trim()}>Vincular destino</button></form>}
 </section><section className="panel"><h2>3. Ativar o chatbot</h2><p>Publique sua automação JRC e selecione-a aqui. Atendimento humano interrompe as respostas automáticas da conversa.</p>
 {binding?<><p>{statusLabel[binding.status]} · versão {binding.version}</p>{canManage&&<div className="button-row"><button disabled={busy} onClick={()=>void changeBinding(binding.status==='ACTIVE'?'PAUSED':'ACTIVE')}>{binding.status==='ACTIVE'?'Pausar novas entradas':'Retomar novas entradas'}</button><button disabled={busy} onClick={()=>void changeBinding('DISABLED')}>Desvincular automação</button><Link to={`/automations/${binding.automationId}/executions`}>Gerenciar execuções</Link></div>}</>:<p>Nenhuma automação vinculada.</p>}
 {canManage&&<form className="form-grid" onSubmit={event=>void bindAutomation(event)}><label>Automação publicada<select value={automationId} onChange={event=>setAutomationId(event.target.value)}><option value="">Selecione</option>{automations.map(item=><option key={item.id} value={item.id}>{item.name} · v{item.activeVersion}</option>)}</select></label><button className="button button--primary" disabled={busy||!automationId}>Vincular automação</button></form>}<Link to="/automations">Criar ou importar automação</Link></section></>}
 {canManage&&channel.provider==='QR'&&<section className="panel"><h2>Gerenciar cadastro</h2><p>Arquivar retira a caixa da lista ativa e preserva mensagens e auditoria. Não apaga caixas no sistema de atendimento.</p><button className="button button--danger" disabled={busy} onClick={()=>void archive()}>{archived?'Restaurar cadastro':'Arquivar cadastro'}</button></section>}
 </>}
 </section>;
}
