import { useEffect,useState,type FormEvent } from 'react';
import { useApiClient,useSession } from '../auth/SessionProvider.js';
import { ApiClientError } from '../api/client.js';

type Credential={id:string;name:string;type:string;status:'ACTIVE'|'REVOKED';revision:number;keyVersion:number;fingerprint:string;lastTestedAt:string|null;updatedAt:string};
const kinds=['HTTP_HEADER','BEARER','BASIC','POSTGRES','MYSQL','AI_PROVIDER','GENERIC_JSON'] as const;
const message=(error:unknown)=>error instanceof ApiClientError?`${error.message}${error.requestId?` Solicitação: ${error.requestId}`:''}`:'Não foi possível concluir.';
export function CredentialsPage(){const client=useApiClient(),{session}=useSession(),[items,setItems]=useState<Credential[]>([]),[name,setName]=useState(''),[type,setType]=useState<(typeof kinds)[number]>('BEARER'),[secret,setSecret]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const editable=Boolean(session&&['OWNER','ADMIN'].includes(session.activeOrganization.role));
 const refresh=async()=>setItems((await client.request<{data:Credential[]}>('/v1/credentials')).data);useEffect(()=>{void refresh().catch(reason=>setError(message(reason)));},[client]);
 async function create(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const parsed=JSON.parse(secret) as Record<string,unknown>;await client.request('/v1/credentials',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({name,type,secret:parsed,metadata:{}})});setName('');setSecret('');setNotice('Credencial criada. O segredo foi removido do formulário.');await refresh();}catch(reason){setError(reason instanceof SyntaxError?'Informe o segredo como objeto JSON válido.':message(reason));}finally{setBusy(false);}}
 async function action(path:string,init:RequestInit,success:string){setBusy(true);setError('');try{await client.request(path,init);setNotice(success);await refresh();}catch(reason){setError(message(reason));}finally{setBusy(false);}}
 return <section className="automation-page"><header className="automation-page-header"><div><span>SEGURANÇA</span><h1>Credenciais</h1><p>Segredos criptografados por empresa. O valor nunca volta ao navegador.</p></div></header>{error&&<p role="alert" className="flows-alert flows-alert--error">{error}</p>}{notice&&<p className="flows-alert">{notice}</p>}{editable&&<details><summary>Nova credencial</summary><form className="credential-form" onSubmit={event=>void create(event)}><label>Nome<input required value={name} onChange={event=>setName(event.target.value)}/></label><label>Tipo<select value={type} onChange={event=>setType(event.target.value as typeof type)}>{kinds.map(kind=><option key={kind}>{kind}</option>)}</select></label><label>Segredo em JSON<textarea aria-label="Segredo em JSON" required value={secret} onChange={event=>setSecret(event.target.value)} placeholder={'{"token":"…"}'}/></label><button className="flows-primary" disabled={busy}>Salvar credencial</button></form></details>}<div className="automation-cards">{items.map(item=><article key={item.id}><span className="flows-badge">{item.status}</span><h2>{item.name}</h2><p>{item.type} · chave v{item.keyVersion} · impressão {item.fingerprint}</p><small>Atualizada {new Date(item.updatedAt).toLocaleString('pt-BR')}{item.lastTestedAt?` · testada ${new Date(item.lastTestedAt).toLocaleString('pt-BR')}`:''}</small>{editable&&item.status==='ACTIVE'&&<div className="flows-actions"><button disabled={busy} onClick={()=>void action(`/v1/credentials/${item.id}/test`,{method:'POST',body:'{}'},'Teste concluído.')}>Testar</button><button disabled={busy} onClick={()=>{const next=window.prompt('Novo segredo em JSON');if(next)try{void action(`/v1/credentials/${item.id}`,{method:'PUT',body:JSON.stringify({revision:item.revision,secret:JSON.parse(next)})},'Credencial rotacionada.');}catch{setError('JSON inválido.');}}}>Rotacionar</button><button disabled={busy} onClick={()=>void action(`/v1/credentials/${item.id}`,{method:'DELETE',body:JSON.stringify({revision:item.revision})},'Credencial revogada.')}>Revogar</button></div>}</article>)}</div>{!items.length&&<p className="flows-empty">Nenhuma credencial cadastrada.</p>}</section>}
